- build-clang.sh
- build-common.sh
- build-compiler-rt.sh
- build-misc.sh
- build-newlib.sh
- build.sh
- config.sh
- configure-toolchain.sh
- package-toolchain.sh
- prepare-source.sh
- scripts/repos.py
- scripts/setup.py
- setup.sh
Many scripts had a #! line below the license text, where it has no
effect: the kernel only looks for #! at the very start of the file.
Without that, an executable script will only run successfully if the
shell it's launched from contains fallback processing of some kind for
when the exec system call fails.
Now all bash and Python scripts have an appropriate #! at the very
start, and all of them are consistently marked executable (a few were
missing that as well).
> Fix shebangs and x bits on all scripts.

- versions.yml
Upstream llvm renamed the master branch to main, this updates the
reference to match.
> Change llvm master reference to main

- setup.sh
We currently require 3.5, which happens to be the default for
Ubuntu Xenial:
python3/xenial,now 3.5.1-3 amd64 [installed,automatic]
Also add an intermeddiate var for the python3 command so
it can be something other than "python3".
This isn't so important now, but Python3 is EOL:
DEPRECATION: Python 3.5 reached the end of its life on September 13th,
2020.
So we'll probably move to 3.6 at some point. Meaning
people who install that from an extra repo won't have
it as "python3" but "python3.6". This saves them some hassle.
Ideally you'd be able to tell venv to use that new Python.
However when you use the "python -m venv" style it will only
use the python it's running on.
> Check Python version before continuing in setup.sh

- build-compiler-rt.sh
- build-newlib.sh
- configure-toolchain.sh
Upstream LLVM was changed in 275592e714130345a481a5cb889c89b73a98614f to
specify a default path for sysroot when targeting bare metal.
This default path is DRIVER_PATH/lib/clang-runtimes/TARGET.
In order to shorten our own modifications on top of LLVM, present in
patches/, this patch reorganises our installation directory's hierarchy.
Newlib and compilerrt now install to the default path, and --sysroot is
removed from our configuration files.
It would be ideal to remove our entire local patch altogether. However,
our configuration files still rely on our patch in order to specify
relative paths to crt0 and -L.
> Change sysroot to DRIVER_PATH/lib/clang-runtimes

- versions.yml
The build scripts have been updated to reflect the new sysroot used in
LLVM (see commit 91cee46ca7610c1de9084f8089300ec98c866965). This
change bumps the LLVM tag used in the 0.1 version of the toolchain to
llvmorg-12.0.0-rc3 to make it compatible with the build scripts.
> Update the LLVM tag for version 0.1 to llvmorg-12.0.0-rc3

- configure-toolchain.sh
After 73e1bdf4601d63b6bba47fe28e86b1e61401a461, sysroot defaults to
DRIVER_PATH/lib/clang-runtimes/TARGET_TRIPLE. This is also the library
path used to find the 'rdimon' library.
Currently we specify this library path to make 'rdimon' searchable. But
since the sysroot change, it shouldn't be necessary anymore.
Closes #9
> Remove -L from configuration files

- build-compiler-rt.sh
- build-newlib.sh
- config.sh
- configure-toolchain.sh
- patches/llvm-0.1.patch
- patches/newlib-0.1.patch
I've added a number of armv7 and armv8 target configurations to the buildscript. To account for more than one options, I've added an environment variable, `LIBRARY_SPEC`, that can be populated with the following values:
armv8.1m.main_hard_fp_mve
armv8.1m.main_hard_fp_nomve
armv8.1m.main_soft_nofp_nomve
armv8m.main_hard_fp
armv8m.main_soft_nofp
armv7em_hard_fpv4_sp_d16
armv7em_hard_fpv5_d16
armv7em_soft_nofp
armv7m_soft_nofp
armv6m_soft_nofp
hard and soft stand for fp linkage
They all build correctly with newlib and compiler-rt, and seem to do the right thing with regards to compiler-rt floating-point files to choose from: do we support double float, just single float, or neither of these.
At least two things I'd like input on:
- are we happy with these options for v7 and v8
- are we happy …
> support for v7 and v8 targets

- patches/newlib-0.1.patch
newlib's ieeefp.h determines floating-point endianness by checking the
\_\_VFP_FP__ macro. If this macro is defined, then newlib assumes that the
target architecture uses the VFP architecture for FPs. In this sort of
arch, IEEE FP values have their word-level endianness the same as their
byte-level endianness.
For example, a double-precision FP value of 1 would be represented in
memory like this (in little-endian ARM targets):
<- lowest addr    highest addr ->
1  0  0  0 | 0  0  0  0
Otherwise, i.e. if \_\_VFP_FP__ macro is undefined, then newlib assumes the
FPA architecture for FPs instead. In this case, IEEE FP values are
always big-endian at word level, while at the byte-level they follow the
target architecture's endianness.
For example, the same double-precision FP value of 1 would …
> Add special case for Clang in deciding floating-point endianness

- .gitignore
- README.md
- scripts/.pylintrc
- scripts/build.py
- scripts/cfg_files.py
- scripts/check.py
- scripts/config.py
- scripts/execution.py
- scripts/make.py
- scripts/repos.py
- scripts/setup.py
- scripts/tarball.py
- scripts/util.py
- setup.sh
This patch ports all functionality implemented as shell scripts to
Python with the following exceptions:
- build-misc.sh is not ported because it is unused
- source tarballs are not built because they need some rework: the
Python scripts support out-of-tree build, whereas the current source
tarball generation method relies on LLVM and newlib repositories
being checked out in the main source tree
- lldb is not built because it is not being installed
The new scripts add several important new features:
- Control over locations of all directories related to the build
process: source, external repositories, build directory, install
directory, target directory for tarballs (out-of-tree build)
- Incremental builds
- Ability to specify a list of targets to build libraries for
- Two levels of …
> Port build scripts from bash to Python

- scripts/build.py
- scripts/check.py
- scripts/config.py
1. Fix handling of --variants all (the default value)
2. Correctly parse Clang versions which include git tag, e.g.
"clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)"
3. Use /usr/bin as the default host toolchain directory, this allows
building on both Ubuntu 18.04 and 20.04 without having to specify
the toolchain directory manually.
> Miscellaneous bug fixes in Python build scripts

- scripts/make.py
Newlib incremental build fails if the configure script was not rerun
after LLVM installation. This patch fixes the issue by always running
the configure script.
> Fix newlib rebuild

- README.md
- scripts/build.py
- scripts/check.py
- scripts/config.py
- scripts/make.py
The first patch adds support for host toolchain kind selection (and GCC as an example). The second patch (--build-mode) just makes life a bit easier when switching between host toolchains.
> Prerequisite patches for cross-compilation support

- scripts/build.py
> When not specifying a revision argument, the default should be 0.1

- .gitignore
- README.md
- scripts/.pylintrc
- scripts/build.py
- scripts/check.py
- scripts/config.py
- scripts/make.py
- scripts/tarball.py
This patch adds support for cross-compiling the Arm toolchain using
Mingw-w64 (targeting x86-64 Windows).
LLVM build requires a native toolchain because it needs a native
tablegen binary during build. For this reason build.py now has
two additional options: --native-toolchain and --native-toolchain-dir.
Cross-build of LLVM only requires native tablegen and llvm-config.
Runtime libraries (compiler-rt and newlib) need a full native
toolchain to be built. Currently we always build full native LLVM when
performing cross-compilation. In the future we might want to only
build tablegen and llvm-config if the user did not request to build
the runtime libraries.
Native Windows build has not been implemented yet.
> Add support for Linux -> Windows cross-compilation

- patches/llvm-HEAD.patch
- versions.yml
Previously the changes needing to be done for the llvm codebase was the same for
HEAD and 0.1, so they used the same patch. But as one change in that patch has
been merged upstream, we need separate patch files for the versions.
> add llvm-HEAD patch to follow divergence between 0.1 and head

- patches/newlib-0.1.patch
- scripts/config.py
- scripts/make.py
Previously, as suggested on the newlib website, we used the
`--enable-newlib-hw-fp` flag to toggle between libm directories and also used
this flag to not use Arm floating point instructions.
However it turns out that that alternate fp libm directory is part of an
experiment that has been abandoned. The right way to address this is to check
for the availability of floating point in the C file itself. Also because this
won't be disruptive for current uses of the library.
I also added a new llvm patch file for HEAD, as since we've merged a fix
upstream, 0.1 and HEAD, differ in what patch needs to be applied to them.
> redid newlib patch for hardfp libm failures

- scripts/setup.py
The scripts list should only contain Python scripts that need to be
installed in the bin directory of the Python sandbox.
This fixes the build of Python sandbox (virual environment) with
Python 3.6.
> Fix the list of scripts in setup.py

- patches/newlib-HEAD.patch
- versions.yml
As some newlib changes we did for the LLVM Embedded toolchain have been merged
upstream, we need a separate Newlib patch file for HEAD.
> add Newlib patch file for HEAD

- README.md
- samples/Makefile.conf
- samples/README.md
- samples/src/baremetal-semihosting/Makefile
- samples/src/baremetal-semihosting/README.md
- samples/src/baremetal-semihosting/make.bat
- samples/src/baremetal-uart/Makefile
- samples/src/baremetal-uart/README.md
- samples/src/baremetal-uart/make.bat
- samples/src/basic-semihosting/Makefile
- samples/src/basic-semihosting/README.md
- samples/src/basic-semihosting/make.bat
This patch series tidies up documentation and Makefiles of the code samples and adds support for building and running the samples on Windows.
> Support building and running code samples on Windows

- scripts/make.py
This patch changes the newlib build so that startup code calls
__libc_init_array (a function which traverses the .init_array section
and calls static object constructors).
> Fix C++ static initialization

- README.md
- scripts/build.py
- scripts/config.py
- scripts/execution.py
- scripts/make.py
- tests/Makefile.conf
- tests/smoketests/Makefile
- tests/smoketests/basic-semihosting/Makefile
- tests/smoketests/basic-semihosting/hello.c
- tests/smoketests/basic-semihosting/stdout
This patch adds a 'test' phase to the build system.
For now we have added one smoke test, which is the same as
baremetal-semihosting from the 'samples' directory.
If qemu-arm is present in PATH, tests are built and run. Otherwise,
they are only built.
Output checking is done using golden files. Each smoke test must have
one stdout and one stderr file that contain the expected outputs, which
are in turn checked against the test output.
This current test framework requires 'make' installed and in PATH.
> Add tests to the build process

- scripts/build.py
- scripts/make.py
Test failures now raise an exception. As consequence of that, build.py
now exits with code 1 in such case.
> Raise exception on test failures

- samples/src/baremetal-semihosting/Makefile
- samples/src/baremetal-uart/Makefile
- samples/src/basic-semihosting/Makefile
- scripts/cfg_files.py
- scripts/make.py
- tests/smoketests/basic-semihosting/Makefile
Currently every library variant we build goes into a folder differentiated
by llvm target triple.But when building consecutive libraries that have the
same target triple but differ in other attributes (ex. soft vs hard fp),
the files will overwrite each other in the same directory.
This issue is fixed by
* Changing the default installation path from INSTALL_DIR/lib/clang-runtimes/TARGET
to INSTALL_DIR/lib/clang-runtimes/LIBRARY_SPEC_NAME .
* Also need to mention the sysroot to this new path.
* Since the default sysroot is changed, need to add the library and header path in the
configuration files.
Change-Id: Ie86564d00695f3c391953cf12f42b64cf829e5ed
> Fixing the overwrite issue of multiple library builds

- samples/src/baremetal-semihosting/make.bat
- samples/src/baremetal-uart/make.bat
- samples/src/basic-semihosting/make.bat
make.bat contained configuration file names that were outdated due do the recent changes to multilib support.
This is the fix. Tested in Windows (with PowerShell).
> Fix config file names in Windows samples scripts

- tests/smoketests/cpp-basic-semihosting/Makefile
- tests/smoketests/cpp-basic-semihosting/hello.cpp
- tests/smoketests/cpp-basic-semihosting/stdout
Adding a c++ test to the smoke tests that compiles and
runs a "Hello world" program which makes use of the
std::string feature of c++ standard library.
> Add one c++ smoke test.

- scripts/check.py
Debian version of Clang is named 'Debian clang' in version string,
which fails the assertion that version string must start
with 'clang version'.
Also, relying on Clang version being the third word is no longer valid,
as there might be a 'Debian' prefix.
------------------
As for the backward compatibility:
```python3
In [1]: import re
In [2]: vers = [ 'clang version 10.0.0-4ubuntu1',
...: 'clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)',
...: 'clang version 3.8.0-2ubuntu4 (tags/RELEASE_380/final)',
...: 'Debian clang version 11.0.1-2', ]
In [3]: [ re.search(r'version (\S+?)(-.*)', v).group(1) for v in vers ]
Out[3]: ['10.0.0', '6.0.0', '3.8.0', '11.0.1']
```
> Fix check.py for Debian Clang

- patches/llvm-HEAD.patch
The current version no longer applies cleanly because of the changes
in the libc++ math.h header related to the implementation of the
copysign functions.
> Update the LLVM patch (HEAD version)

- patches/llvm-13.patch
- patches/llvm-HEAD.patch
- scripts/build.py
- scripts/config.py
- scripts/package.py
- scripts/repos.py
- scripts/util.py
- versions.yml
This series of patches implements a new build script action "package-src" which creates a source package containing a copy of the build scripts bundled with LLVM and newlib source code.
It also adds support for building the toolchain from such source packages.
> Implement creation of source packages and building from source packages

- patches/llvm-HEAD.patch
- versions.yml
The patches update llvm-HEAD.patch to accommodate upstream changes in libc++ headers.
> Fix HEAD build, two more patches

- scripts/make.py
- versions.yml
Upstream change https://reviews.llvm.org/D119255 drops support for
standalone builds of libc++abi and libc++. The new way to build these
libraries is to invoke CMake using the source root directory
'runtimes', not 'libcxx' or 'libcxxabi'.
This patch updates the scripts to build libc++ and libc++abi
correctly, the additional benefit is that libc++ and libc++abi are now
built in one go.
Unfortunately, compiler-rt cannot be built in the same way because it
is incompatible with the workaround that involves manually setting
CMAKE_SYSTEM_NAME (which is needed for AArch64, see commit
cd997482aff515872b9938a9d529ee2b2447ae29).
> Use new method to build libc++abi and libc++

- patches/newlib-HEAD.patch
- scripts/make.py
- versions.yml
The newlib change 437c5c5085ff30b4a4960b2b53d06728c788361d renamed
HAVE_INIT_FINI to _HAVE_INIT_FINI and HAVE_INITFINI_ARRAY to
_HAVE_INITFINI_ARRAY.
This patch adjusts the build scripts by adding -U_HAVE_INIT_FINI to
compiler flags (alongside with -UHAVE_INIT_FINI which we need to keep
in order to build older newlib versions).
The patch also renames HAVE_INITFINI_ARRAY to _HAVE_INITFINI_ARRAY in
assembly files (this part should be upstreamed at some point).
> Fix newlib breakage related to INIT_FINI

- patches/newlib-HEAD.patch
- versions.yml
Upstream newlib commit 063d67faf0266e5ba169bc5cfde8aed011b1d41b fixes
the issue with HAVE_INITFINI_ARRAY (the macro had been renamed in
configure scripts and C source code, but not in startup code written
in assembly), so we no longer need a downstream fix for it.
> Update newlib-HEAD.patch, startup code

- patches/newlib-HEAD.patch
- versions.yml
Upstream newlib commit d5a20f0b70c73c72ec2bc4b639815bb821859255
merges libgloss/libnosys/configure into libgloss/configure. The new
configure script uses a proper check for ELF support rather than
checking that the target triple ends with "-elf" (which gives
incorrect result for "arm-*-eabi").
Because of the change we no longer need a downstream patch for the
configure script.
> Update newlib-HEAD.patch, remove libgloss/libnosys/configure

- versions.yml
A prior commit b4aa4b716dc3c1b4923b57c048b5e0e79c13ca5c changed the
HEAD build configuration in versions.yml to use hard-coded commits of
LLVM and newlib, so that build breakages could be fixed one by one.
Now that all breaking changes have been addressed, we can restore the
HEAD configuration to track the tips of upstream branches as before.
> Remove hard-coded commit hashes from versions.yml HEAD config

- versions.yml
This reverts commit 798361a321e7aa13cdc0d867548cf582d0037a12.
The commit causes build failure on machines that don't have 'makeinfo'
(part of 'texinfo' package) installed.
> Revert "Remove hard-coded commit hashes from versions.yml HEAD config"

- patches/newlib-HEAD.patch
- versions.yml
Starting with upstream newlib commit
492e5fe8b0863e15ffd5a269e42b60fabfc5f5db newlib build started failing
on machine that don't have makeinfo (part of texinfo package)
installed when trying to build the file libgloss/doc/porting.info.
We don't provide newlib docs as part of our distribution, so makeinfo
should not be required. This patch fixes the issue by creating an
empty libgloss/doc/porting.info file.
> Fix newlib build failure

- versions.yml
The newlib commit we are currently using has stale
libgloss/aclocal.m4 file, and because of this build fails on machines
that don't have autotools installed.
This patch fixes the issue by changing newlib commit to point to a
commit in which files generated by autotools have been been updated.
> Use newlib commit that does not require autotools

- scripts/repos.py
- versions.yml
This series contains two patches:
* A small fix for incremental builds
* Removal of hard-coded commit hashes from versions.yml HEAD config
> Fix HEAD build

- patches/llvm-HEAD.patch
Required because of a change in libcxx to uglify parameter names.
https://reviews.llvm.org/D129051
> Fix patch for LLVM HEAD

- scripts/make.py
Newlib only declares long double functions like cosl if long double is
equivalent to double. On AArch64 long double is twice the size of double
so the declarations are missing. However Newlib's build system still
tries to compile the long double code.
The LLVM change https://reviews.llvm.org/D122983 means that clang no
longer implicitly declares functions by default. Therefore use
-Wno-implicit-function-declaration to work around the problem.
Ideally Newlib's build system would be fixed, but since we plan on
switching to picolibc (which doesn't have this problem) just use this
workaround instead of fixing it properly.
> Build newlib with -Wno-implicit-function-declaration

- scripts/config.py
e.g. armv6m_soft__nofp -> armv6m_soft_nofp
> Fix erroneous underscore in library variant names

- docs/building-from-source.md
- scripts/build.py
- scripts/config.py
The smoke tests use the install dir, which meant that deleting the build
dir didn't assure a valid test result.
When compared to other build systems this is surprising.
By moving the install dir into the build dir the expectation that
deleting the build dir will cause tests to use fresh build output is
upheld.
For consistency, also default to putting the package tar.gz in the build
directory.
> Move default install location into build dir

- patches/llvm-HEAD.patch
A change in the cmath header meant the patch didn't apply cleanly.
> Update LLVM patch

- scripts/cfg_files.py
- scripts/make.py
Running `clang --config <arch>.cfg --print-libgcc-file-name` now returns
a correct path for a compiler-rt builtins archive for the given
architecture.
GitHub issue #109
> Introduce -resource-dir flag to config files

- scripts/cfg_files.py
- scripts/make.py
This reverts commit 316c635e48b53f3ba8e3ee00444d0cfb467aff6d.
The change caused this error while running `build.py test`:
```
In file included from hello.c:1:
In file included from /work/LLVM-embedded-toolchain-for-Arm/build-HEAD/install/LLVMEmbeddedToolchainForArm-HEAD/bin/../lib/clang-runtimes/armv6m_soft_nofp/include/stdio.h:44:
In file included from /work/LLVM-embedded-toolchain-for-Arm/build-HEAD/install/LLVMEmbeddedToolchainForArm-HEAD/bin/../lib/clang-runtimes/armv6m_soft_nofp/include/inttypes.h:17:
/work/LLVM-embedded-toolchain-for-Arm/build-HEAD/install/LLVMEmbeddedToolchainForArm-HEAD/bin/../lib/clang-runtimes/armv6m_soft_nofp/include/sys/config.h:34:10: fatal error: 'float.h' file not found
#include <float.h>
^~~~~~~~~
1 error generated.
Makefile:21: recipe for target …
```
> Revert "Introduce -resource-dir flag to config files"

- samples/src/baremetal-uart/hello.c
When run on micro:bit v1 hardware it lost most of the characters - now fixed.
> Stabilise baremetal-uart sample

- scripts/repos.py
Applying the picolibc patch creates new files.
If those files exist when applying the patch a second time then patching will fail because Git refuses to overwrite existing files.
> Fix re-patching picolibc

- CHANGELOG.md
- README.md
- samples/src/baremetal-semihosting/Makefile
- samples/src/baremetal-semihosting/make.bat
- samples/src/baremetal-uart/Makefile
- samples/src/baremetal-uart/make.bat
- samples/src/cpp-baremetal-semihosting/Makefile
- samples/src/cpp-baremetal-semihosting/make.bat
- tests/smoketests/basic-semihosting/Makefile
- tests/smoketests/cpp-basic-semihosting/Makefile
Since https://reviews.llvm.org/D134208 --config armv6m_soft_nofp_semihost no longer works because the feature to automatically append .cfg was removed. This breaks the smoke tests and the documented behaviour of BMT. Fix by added .cfg suffix to every --config option in documentation and examples.
> .cfg suffix is no longer automatically added to --config

- CHANGELOG.md
- CMakeLists.txt
- cmake/THIRD-PARTY-LICENSES.txt.in
- cmake/VERSION.txt.in
- cmake/config.cfg.in
- cmake/generate_version_txt.cmake
- cmake/handle-windows-symlinks.sh
- cmake/meson-cross-build.txt.in
- docs/building-from-source.md
This makes building much faster (a no-op build takes seconds instead of minutes) and should be make building more familiar for LLVM developers.
> Enable building directly with CMake

- CMakeLists.txt
- scripts/make.py
Clang's default C++ standard is now gnu++17 instead of gnu++14.
Supporting C++17 requires aligned new & delete. Implementing this
requires posix_memalign. Picolibc only provides posix_memalign if the
correct feature test macros are set.
https://www.gnu.org/software/libc/manual/html_node/Feature-Test-Macros.html
>  Fix "undefined symbol: operator new"

- CMakeLists.txt
This permits including LLVM-embedded-toolchain-for-Arm within another umbrella project.
> Fixes for when CMAKE_CURRENT_BINARY_DIR != CMAKE_BINARY_DIR

- CMakeLists.txt
In an incremental build the install messages were drowning out the useful output so default to disabling them.
Second commit: Store files in tar.gz in	ArmCompiler-.../ directory
> Default to silent install

- CMakeLists.txt
This commit adds a variable 'libc_type' set at the start of the loop over library variants, and moves the picolibc build subproject definition into an if statement that conditions on libc_type. So it's easy to apply a downstream patch that varies libc_type (perhaps per library variant) and adds an extra clause to provide a build subproject for the alternative library.
I've moved a lot of the LLVM runtimes configuration options into a variable 'libc_specific_runtimes_options', which is set inside the if statement that tests libc_type. Rationale: a different libc might provide a different set of functionality, and permit a different set of libc++'s optional pieces to be enabled.
No functional change. As long as libc_type is unconditionally set to 'picolibc', which it is in this commit, …
> Add infrastructure for using different C libraries.

- CMakeLists.txt
- patches/picolibc-HEAD.patch
- tests/smoketests/cpp-basic-semihosting/hello.cpp
Doing so requires enabling GNU extensions in picolibc since libc++ uses
functions like strtof_l that take a locale argument. These functions are
called from inline functions so we must enable them globally instead of
passing an argument only when building libc++. An alternative option is
to set _GNU_SOURCE in libc++'s __config_site header but that would mean
different sets of functions would be declared depending on the ordering
of includes.
Picolibc's tinystdio doesn't include strtoll_l or strtoull_l so this
change adds those. They behave in the same way as tinystdio's strtof_l
which discards the locale argument.
The C++ smoke test now includes all the C++ headers it can to make it
more obvious what can and cannot be included. As you'd expect,
filesystem, threading and wchar related …
> Enable localisation

- patches/picolibc-HEAD.patch
These functions have been added in upstream picolibc
> Fix strto*l_l being defined twice

- CHANGELOG.md
- README.md
Also update the change log. Support for C++17's aligned operator new was added with the switch to picolibc.
> Update C++ support info in README

- CMakeLists.txt
This changes the filename from libclang_rt.builtins-<ARCH>.a to simply libclang_rt.builtins.a.
> Build compiler-rt without arch in its filename

- CMakeLists.txt
If CMake is run with -DMESON_EXECUTABLE=/path/to/meson then that path should be used.
> Allow using a meson executable not in path

- patches/picolibc-HEAD.patch
The error began with picolibc change
98486a5bbd4f76d45f311b0d950a116c08503938.
The consequence of this workaround is that thread local storage is likely broken.
> Work around "unable to move location counter backward for: .tbss_space"

- CHANGELOG.md
- CMakeLists.txt
- README.md
- samples/ldscripts/armv4t.ld
- samples/ldscripts/armv5te.ld
LLD and compiler-rt support for these has recently been added to LLVM.
> Also build toolchains for Armv4T, Armv5TE and Armv6

- test-support/llvm-libc++-picolibc.cfg.in
- test-support/llvm-libc++abi-picolibc.cfg.in
- test-support/llvm-libunwind-picolibc.cfg.in
This patch updates picolibc-specic libc++, libc++abi and libunwind lit.cfg.py files to match upstream change
https://reviews.llvm.org/D144031.
> Rename libcxx.test.newconfig -> config

- CMakeLists.txt
- test-support/llvm-libc++-picolibc.cfg.in
- test-support/llvm-libc++abi-picolibc.cfg.in
- test-support/llvm-libunwind-picolibc.cfg.in
When building libc++, libc++abi and libunwind tests we need to manually add -march= and -mfloat-abi to the compiler command line, merely setting CMAKE_CXX_FLAGS is not enough.
This patch fixes the issue by adding a new CMake variable RUNTIME_TEST_ARCH_FLAGS and using it in test config files.
> Pass -march/-mfloat-abi flags to C++ runtime tests

- CMakeLists.txt
- cmake/meson-cross-build.txt.in
- patches/picolibc.patch
* Add .exe extension to executable paths.
* Remove a unix command from picolibc meson.build.
* Work around other issues by skipping the creation of specs files.
> Enable building on Windows

- CMakeLists.txt
- cmake/meson-cross-build.txt.in
- patches/picolibc.patch
* Update picolibc patch based on feedback from https://github.com/picolibc/picolibc/pull/435
* Avoid calling shell script when building picolibc
* Enable building runtimes on Windows. Also add CMAKE_EXECUTABLE_SUFFIX exhaustively for all executable paths.
> Windows compatibility changes

- README.md
- docs/building-from-source.md
Just a tiny tweak was needed to get building the toolchain for OSX work: For the runtimes component, which builds libcXX*, including libunwind, we need to disable the APPLE CMake variable that will configure various bits for an assumed Apple target. It doesn't seem possible to disable this without directly editing the source.
Testing has been restricted to building the variants, running the `ninja check-llvm-toolchain' script (qemu runs produce the expected results) and doing some ad-hoc compiling for the targets.
Preferably we should handle this properly in LLVM proper, but accounting for the APPLE variable in a non-hacky way seems like a hairy affair, which will take more effort. Patching the source here seems like an acceptable band-aid for supporting a platform that we have had …
> Add experimental support for OSX host

- patches/llvm-project.patch
This is effectively a cherry-pick of https://reviews.llvm.org/D145443: Use LLVM_USE_SYMLINKS option in install_symlink
> Fix symlinks being generated in Windows build

- CMakeLists.txt
- cmake/copy_target_libraries.py
Building the libraries on Windows can take hours, compared to minutes on Linux. Therefore this change allows copying libraries from another build.
The new PREBUILT_TARGET_LIBRARIES CMake option causes the building of libraries to be skipped, with the assumption that the libraries will be added in the location in which they would normally be built.
The copy_target_libraries.py script can be used to copy the libraries from a previously built package.
> Allow copying libraries from another build

- CMakeLists.txt
Replace it with some code to set CMAKE_C_COMPILER_LAUNCHER and CMAKE_CXX_COMPILER_LAUNCHER if ccache is found and the variables aren't already set.
> LLVM_CCACHE_BUILD is deprecated

- CMakeLists.txt
Stripping removes code signatures. Therefore if stripping needs to be done it must be done prior to signing, and not at package creation time.
> Don't strip binaries when creating package

- CMakeLists.txt
Upstream patch https://reviews.llvm.org/D122941 changed debug mode to a configuration-time option, so the LIBCXX_ENABLE_DEBUG_MODE_SUPPORT variable is no longer used.
> Remove LIBCXX_ENABLE_DEBUG_MODE_SUPPORT

- versions.json
* Use llvm-project version 16.0.0 tag.
* picolibc hasn't been released since December and has important recent changes so use the latest revision.
> Freeze llvm-project and picolibc sources.

- CMakeLists.txt
In read_repo_version in CMakeLists.txt we look at versions.json to know what version of a repo we should check out. We can specify the version type be either commithash, branch or tag. Currently we add "origin/" to the version string if the type is either branch or tag. However for tag this isn't the right syntax. Removing origin will properly check out the repo by tag.
> don't add "origin/" when checking out a tag

- CMakeLists.txt
- cmake/THIRD-PARTY-LICENSES.txt.in
- cmake/VERSION.txt.in
- cmake/generate_version_txt.cmake
- docs/building-from-source.md
Previously separate source packages were published which is no longer the case, instead we just refer to the GitHub repos and their revisions.
> Clarify docs referring to sources.

- CHANGELOG.md
- CMakeLists.txt
- cmake/multilib.yaml.in
- patches/llvm-project.patch
This PR cherry-picks to the llvm-16 branch @mplatings 's not-yet-committed support for YAML-configured multilib setups, and creates one from our existing set of picolibc variants.
The overall effect is to make the `.cfg` files optional, although they're still available to be used if a user prefers. For example, these two commands have the same effect of building a semihosting hello-world program for Armv7-M, with and without a config file:
```
clang --config=armv7m_soft_nofp_semihost.cfg -T picolibc.ld hello.c
clang --target=arm-none-eabi -march=armv7-m -T picolibc.ld -lcrt0-semihost -lsemihost hello.c
```
> Multilib on llvm 16

- CMakeLists.txt
- cmake/config.cfg.in
These are not necessary since the multilib system will find the correct paths automatically.
This necessitates switching from using crt0.o and crt0-semihost.o to instead using libcrt0.a and libcrt0-semihost.a. This is because .o files cannot be found in the linker search directories, whereas .a files can.
> Remove paths to sysroot & crt0 from config files

- CMakeLists.txt
- README.md
- cmake/config.cfg.in
These are no longer necessary since a crt0 library can be found in the library search path.
> Remove paths to crt0 from config files

- samples/README.md
The LLVM Embedded Toolchain for Arm has a macOS release. Update the samples README to claim support and to point the reader to the instructions for installing QEMU.
macOS requires the developer tools to be installed to run the samples, which also installs LLDB. The existing instructions for Linux work for macOS.
> Update samples README with macOS information

- README.md
On macOS when the files are unpacked the com.apple.quarantine will be added to the executable files. Document that user is responsible for removing the attribute and give the user a command to run to do this.
This issue will be addressed in a follow up change.
> Update macOS support level and document how to dequarantine the tools

- README.md
Command incorrectly spelled as com.apple.com.quarantine.
> Fix typo in find command to remove com.apple.quarantine

- cmake/.gitattributes
- cmake/generate_version_txt.cmake
This fixes the source packages that GitHub automatically creates for each release.
Previously building from a source package would fail with:
`fatal: not a git repository (or any parent up to mount point /)`
> Fix building from sources created by git archive

- CMakeLists.txt
- test-support/lit-exec-qemu.py
- test-support/picolibc-lit-test-abort.template
- test-support/picolibc-lit-test-test-except.template
- test-support/picolibc-lit-test.template
- test-support/picolibc-lit.site.cfg.py.in
General concept of enabling lit testing for picolibc.
Do not forget to use external lit for example:
-DLLVM_DEFAULT_EXTERNAL_LIT=$PWD/llvm/bin/llvm-lit
> Lit testing

- CMakeLists.txt
This adds testing for compiler-rt, and begins to collect runtime testing under the target check-llvm-toolchain-runtimes, which can also be used to run testing on specific variants.
There are currently a few tests which fail, which require upstream changes to fix the tests.
> Add compiler-rt testing

- CMakeLists.txt
PR #196 deprecated `LLVM_CCACHE_BUILD` and replaced it with `CMAKE_C_COMPILER_LAUNCHER` and `CMAKE_CXX_COMPILER_LAUNCHER`. However the CMake configuration still uses `LLVM_CCACHE_BUILD` which results in the CMake Warning:
```
Manually-specified variables were not used by the project:
LLVM_CCACHE_BUILD
```
Remove use of `LLVM_CCACHE_BUILD` from the CMake configuration command.
> Remove LLVM_CCACHE_BUILD

- CMakeLists.txt
- tests/ldscripts/picolibc_aarch64.ld
The raspi3b machine has multiple cores, which resulted with code being executed on all the cores in parallel. To avoid this, the qemu machine for aarch64 tests was changed to virt.
> Change machine for aarch64 picolib tests to virt

- CMakeLists.txt
- test-support/lit-exec-qemu.py
The lit-exec-qemu.py script was modified to reproduce the QEMU calls used in picolibc's own tests.
> Run test with QEMU same way as picolibc tests do

- samples/src/baremetal-uart/Makefile
- samples/src/baremetal-uart/hello.c
- samples/src/baremetal-uart/make.bat
- samples/src/cpp-baremetal-semihosting-cfi/hello.cpp
The whole point of this sample is that it runs without semihosting, so it's at least pointless to enable semihosting in the emulator, and perhaps it's also a testing hazard (in that if semihosting were accidentally included in the image, we'd prefer it to fail, so that we notice).
> baremetal-uart sample: turn off QEMU semihosting.

- patches/picolibc.patch
The fragment is no longer needed as the issue it solved is now fixed upstream. Upstream fix: https://github.com/picolibc/picolibc/pull/499
> [picolibc] Remove fragment of patch

- CMakeLists.txt
- test-support/llvm-libc++-picolibc.cfg.in
- test-support/llvm-libc++abi-picolibc.cfg.in
- test-support/llvm-libunwind-picolibc.cfg.in
Previously there would be multiple tests with names like llvm-libc++-picolibc-cfg-in.std/numerics/c_math.cmath.pass.cpp
Now the names will be, for example:
libc++-aarch64.std/numerics/c_math.cmath.pass.cpp
libc++-armv6m_soft_nofp.std/numerics/c_math.cmath.pass.cpp
> Disambiguate variants of tests

- CMakeLists.txt
- cmake/meson-cross-build.txt.in
- test-support/ldscripts/picolibc_aarch64.ld
- test-support/ldscripts/picolibc_armv4t.ld
- test-support/ldscripts/picolibc_armv5te.ld
- test-support/ldscripts/picolibc_armv6m_soft_nofp.ld
- test-support/ldscripts/picolibc_armv7em_hard_fpv4_sp_d16.ld
- test-support/ldscripts/picolibc_armv7em_hard_fpv5_d16.ld
- test-support/ldscripts/picolibc_armv7em_soft_nofp.ld
- test-support/ldscripts/picolibc_armv7m_soft_nofp.ld
- test-support/ldscripts/picolibc_armv8.1m.main_hard_fp.ld
- test-support/ldscripts/picolibc_armv8.1m.main_hard_nofp_mve.ld
- test-support/ldscripts/picolibc_armv8.1m.main_soft_nofp_nomve.ld
- test-support/ldscripts/picolibc_armv8m.main_hard_fp.ld
- test-support/ldscripts/picolibc_armv8m.main_soft_nofp.ld
- test-support/lit-exec-qemu.py
- test-support/picolibc-test-wrapper.py
- test-support/run_qemu.py
Switch from manually building picolibc tests to bilding and running them
as part of picolibc build. This enables tests, which were not included
in the manual build.
Several fixes were necessary:
1. Add '-nostdlib' to picolibc c_args
This prevents errors like:
ld.lld: error: unable to find library -lc
in checks for compiler flags support in picolibs build scripts.
Example of failing check:
has_link_defsym = meson.get_cross_property('has_link_defsym', cc.has_link_argument('-Wl,--defsym=' + global_prefix + '_start=0'))
2. Make picolibc use compiler_rt in place of libgcc.
3. Change machines used with qemu and adjust memory layouts.
Some of picolibc tests need more memory, than previous machines
provided. Example error:
ld.lld: error: section '.text' will not fit in region 'flash': overflowed …
> picolibc: tests with meson

- test-support/picolibc-test-wrapper.py
upstream fix: https://github.com/picolibc/picolibc/pull/504
> [picolibc] Enable math_errhandling test after upstream fix

- CMakeLists.txt
Each library configure step is typically single-threaded so it's desirable to do it in parallel with other tasks. Disabling terminal access for the configure step means that the step will no longer be placed in a Ninja job pool, and therefore can be run in parallel.
This change speeds up the overall build time by 6 minutes.
> Speed up build time

- samples/Makefile.conf
- samples/src/baremetal-semihosting-aarch64/Makefile
- samples/src/baremetal-semihosting-aarch64/make.bat
- samples/src/baremetal-semihosting/Makefile
- samples/src/baremetal-semihosting/make.bat
- samples/src/baremetal-uart/Makefile
- samples/src/baremetal-uart/make.bat
- samples/src/cpp-baremetal-semihosting-cfi/Makefile
- samples/src/cpp-baremetal-semihosting-cfi/make.bat
- samples/src/cpp-baremetal-semihosting-prof/Makefile
- samples/src/cpp-baremetal-semihosting-prof/make.bat
- samples/src/cpp-baremetal-semihosting-ubsan/Makefile
- samples/src/cpp-baremetal-semihosting-ubsan/make.bat
- samples/src/cpp-baremetal-semihosting/Makefile
- samples/src/cpp-baremetal-semihosting/make.bat
Rely on the automatic multilib selection instead.
> Remove use of *.cfg files from samples.

- CMakeLists.txt
This makes it easier to set LLVM_USE_LINKER to a linker other than lld. Without this change, to use a linker other than lld cmake would need to be run with -DLLVM_ENABLE_LLD=OFF -DLLVM_USE_LINKER=...
> Use LLVM_USE_LINKER instead of LLVM_ENABLE_LLD

- CMakeLists.txt
Fix dependency problem between picolibc tests and compiler-rt
The compiler libraries are now copied as part of install step, so they
are available for picolibc tests.
Fix for tests not being run with old meson
> [picolibc] minor fixes for tests

- patches/llvm-project.patch
These patches are upstreamed under https://reviews.llvm.org/D156427 but not present in the release/17.x branch which the llvm-17 bmt release is going to be based on.
> Update patches to fix two failing tests.

- patches/llvm-project.patch
Without these the patch is detected as corrupted and the Windows build fails.
> Restore trailing whitespaces in patch

- CMakeLists.txt
By default the build system will ensure tools like clang are up to date before using them to build libraries. If you are working on changes that are specific to libraries and unlikely to be affected by changes to tools then this behaviour is undesirable as you can spend a lot of time waiting for tools to be rebuilt. By setting LIBS_DEPEND_ON_TOOLS to false the dependency from libraries to tools is removed and the libraries can be built without rebuilding tools.
> Add LIBS_DEPEND_ON_TOOLS option

- test-support/picolibc-test-wrapper.py
Test fma is new test that fails.
Disabled for time of investigation.
> Disable failing picolibc test

- CMakeLists.txt
- cmake/multilib.yaml.in
- test-support/picolibc-test-wrapper.py
The optional FP Unit for ArmV7-M could be one of FPv4-SP and FPv5, FPv4-SP being the lowest common denominator.
So provide the armv7m_soft_fpv4_sp_d16 variant for -mfpu=fpv4-sp-d16.
The math_errhandling test fails as it does for the armv7em_hard_fpv4_sp_d16 variant. So disable it for now.
Make the new armv7m_soft_fpv4_sp_d16 variant the default when -mfloat-abi=softfp is specified.
> Provide Armv7-M softfp library variant

- CMakeLists.txt
- README.md
- packagetest/hello.c
- packagetest/hello.cpp
- samples/Makefile.conf
- samples/src/baremetal-semihosting/make.bat
- samples/src/baremetal-uart/make.bat
- samples/src/cpp-baremetal-semihosting-cfi/make.bat
- samples/src/cpp-baremetal-semihosting-prof/make.bat
- samples/src/cpp-baremetal-semihosting-ubsan/make.bat
- samples/src/cpp-baremetal-semihosting/make.bat
- test-support/picolibc-test-wrapper.py
- test/multilib/armv4t.test
- test/multilib/armv5e.test
- test/multilib/armv6m.test
- test/multilib/armv7m.test
- test/multilib/armv8.1m.main.test
- test/multilib/armv8m.main.test
Added single precision version for v8.1m.main.
> Add explicit "-mfpu=" for AArch32 commands

- samples/src/cpp-baremetal-semihosting-prof/proflib.c
Recent upstream change causes __llvm_profile_raw_version to be defined by the compiler, thus no need to define it in the runtime.
> Fix the profiling sample runtime

- CMakeLists.txt
- test-support/picolibc-test-wrapper.py
Disable long double tests for aarch64
so more tests execute without failure.
> Enable more Picolibc tests on aarch64

- CMakeLists.txt
edit:
current commit message:
```
this patch is fixing two issues:
Currently when figuring out the toolchain package name, we make some wrong
assumptions like the presence of CMAKE_OSX_ARCHITECTURES means a unified
build. Also when CMAKE_OSX_ARCHITECTURES is not present and we are building on
macOS silicon, the package name will be `AArch64`.
Should do some parsing of the CMAKE_OSX_ARCHITECTURES and look at the
CMAKE_SYSTEM_PROCESSOR var, to deduce the right system name.
Basically when CMAKE_OSX_ARCHITECTURES is set and non-empty, this overrides the
system architecture, and we need to figure out if we do a unified build (both
x86_64 and arm64 are specified), or either.
If it's a unified build, use `unified` to make this clear, instead of the
current behaviour of omitting the arch string. …
```
> be more sophisticated about deriving configs from macOS variables 

- samples/src/cpp-baremetal-semihosting-prof/proflib.c
Reverts ARM-software/LLVM-embedded-toolchain-for-Arm#308 since the upstream change was reverted https://github.com/llvm/llvm-project/commit/4d5d9a539058c87b42b472daedfb95377f5e1612
> Revert "Fix the profiling sample runtime"

- CMakeLists.txt
- patches/llvm-project.patch
- test/multilib/aarch64.test
- test/multilib/armv4t.test
- test/multilib/armv5e.test
- test/multilib/armv6m.test
- test/multilib/armv7a.test
- test/multilib/armv7em.test
- test/multilib/armv7m.test
- test/multilib/armv7r.test
- test/multilib/armv8.1m.main.test
- test/multilib/armv8m.main.test
Fixes #307
This allows a multilib configuration to specify explicitly that a subset of its
libraries are alternatives to each other, and at most one of that subset should
be selected. To be consistent with existing semantics, the _last_ choice wins,
if more than one of the options matches the given flags.
> add ExclusiveGroup feature to multilib.yaml

- CMakeLists.txt
- patches/llvm-project.patch
- test/multilib/aarch64.test
- test/multilib/armv4t.test
- test/multilib/armv5e.test
- test/multilib/armv6m.test
- test/multilib/armv7a.test
- test/multilib/armv7em.test
- test/multilib/armv7m.test
- test/multilib/armv7r.test
- test/multilib/armv8.1m.main.test
- test/multilib/armv8m.main.test
Cherry-pick of  #312 to the llvm-17 branch.
The cherry-pick of the patch applies cleanly to `release/17.x` of llvm-project.
There is a slight difference between the compile flags used to build the variants in BMT LLVM-17. So the CMakeLists.txt and the tests needed slight modifications. However nothing complicated.
> Llvm 17 multilib exclusivegroup

- patches/llvm-project.patch
At the moment clang is not generating the correct FPU directive for Arm V8.1m Mainline CPU's when assembled by -S. So when compiled with -S output and `-save-temps=obj` loses MVE feature which leads to assembler error.
There is a mismatch in the default FPU option that Arm V8.1-m CPUs define and what clang generates. For example, Clang generates fpv5-d16 for M85 and what is defined in ARMTargetParser.def is FK_FP_ARMV8_FULLFP16_D16.
This patch add cases for handling this FPU directive as well and thus makes clang generates the right FPU directives for Arm V8.1-m CPUs.
> Compiler's -S output and `-save-temps=obj` loses MVE feature which leads to assembler error for Arm V8.1m Cpus.

- versions.json
Update versions.json to use the following commits.
llvm-project: llvmorg-17.0.1 tag
picolibc: the 41a688944d6f4fc4e5c03c0ad0301b0b4e8f6899 commit-hash This is the picolibc version used for preview-17.0.0-devdrop0.
> [llvm-17] Update versions

- patches/llvm-project.patch
Without the trailing whitespace the patch fails to apply on Windows.
Restore the trailing whitespace.
> [main] Add trailing whitespace to patch without which the Windows build fails

- patches/llvm-project.patch
Cherry-pick of #318 
Without the trailing whitespace the patch fails to apply on Windows.
Restore the trailing whitespace.
> [llvm-17] Add trailing whitespace to patch without which the Windows build fails

- patches/llvm-project.patch
The test llvm/test/CodeGen/ARM/build-attributes.ll needs updating to incorporate the change
https://github.com/ARM-software/LLVM-embedded-toolchain-for-Arm/pull/313.
Changing the expected FPU to fp-armv8-fullfp16-d16 from fpv5-d16.
> Fix llvm/test/CodeGen/ARM/build-attributes.ll test.

- patches/llvm-project.patch
The test llvm/test/CodeGen/ARM/build-attributes.ll needs updating to incorporate the change
https://github.com/ARM-software/LLVM-embedded-toolchain-for-Arm/pull/313.
Changing the expected FPU to fp-armv8-fullfp16-d16 from fpv5-d16.
> Fix llvm/test/CodeGen/ARM/build-attributes.ll test. (#320)

- test-support/picolibc-test-wrapper.py
Two upstream changes:
c368f318 Remove c_args from per-multilib args
acc9b941 scripts: Change run-arm, run-aarch64 and run-riscv arg processing
changed the way comandline arguments are passed in semihosting tests.
Adjusted picolibc-test-wrappter.py to match run-arm used in upstream.
> picolibc: update test wrapper to match upstream

- CMakeLists.txt
I wrapped the existing add_picolibc() function with a macro add_libc(), so that I could conditionally replace it with add_newlib() which has the same API. To avoid having to write out the entire argument list another three times, I made the macro just pass its entire argument list through unchanged using ${ARGN}.
However, it turns out that this _doesn't_ pass the list through unchanged, because the effect is to expand any list parameters into lots of individual arguments, the same way that $* does in POSIX sh. So 'test_executor_params', which contains multiple qemu options, was being broken up and distributed between all the subsequent default_* parameters, causing chaos at test time.
In sh, you avoid unwanted argument splitting by writing "$@" instead of $*, but I don't know of any …
> Fix cmake argument-passing bug in the newlib patch.

- CMakeLists.txt
- docs/building-from-source.md
- patches/llvm-project/0001-Fix-llvm-test-CodeGen-ARM-build-attributes.ll-test.patch
- patches/llvm-project/0002-libc-Add-check-for-building-with-picolibc.patch
- patches/llvm-project/0003-Run-picolibc-tests-with-qemu.patch
- patches/llvm-project/0004-xfail-two-remaining-libcxx-with-picolibc-tests.patch
- test-support/lit-exec-qemu.py
- test-support/llvm-libc++-picolibc.cfg.in
- test-support/run_qemu.py
Added patches from reviews in upstream.
https://reviews.llvm.org/D154246 (build)
https://reviews.llvm.org/D155521 (run with qemu)
Split llvm-project patches, so it is easier to track them.
Updated lit configuration.
> Add patches to make some libcxx armv7m tests pass

- CMakeLists.txt
My initial patch to add the newlib-overlay mode didn't change the archive name. So the newlib overlay archive would get the same name as the archive that would be built in the ordinary whole-toolchain mode, e.g. 'LLVMEmbeddedToolchainForArm-18.0.0-Linux-x86_64.tar.xz'.
That's semantically misleading (it suggests there's a whole toolchain in the archive), and worse, it means the two files can't be downloaded into the same directory without colliding.
Also, the newlib overlay package unpacked its files into a top-level directory called 'LLVMEmbeddedToolchainForArm-18.0.0-Linux-x86_64'. That's fine if you're unpacking it over the top of the Linux-x86_64 package of the main toolchain, but if you're trying to install the newlib overlay on a different platform, then the two top-level …
> Adjust file and path names of the newlib overlay package.

- patches/llvm-project/0002-Add-check-for-building-with-picolibc.patch
- patches/llvm-project/0003-Run-picolibc-tests-with-qemu.patch
No functional changes. The patches failed to apply due to changed width of text based table.
> rebase llvm patches

- patches/llvm-project/0002-Add-check-for-building-with-picolibc.patch
This test started passing after the following commit.
Therefore removing the XFail from patches/llvm-project/0002-Add-check-for-building-with-picolibc.patch 
```
commit e11148fda6d8c0eec496463adb46fd6f03a91081
Revert recent changes to test_demangle.pass.cpp
These tests do not need to be updated when making changes to the API.
```
> Remove XFAIL: libcxxabi/test/test_demangle.pass.cpp

- patches/llvm-project/0002-Add-check-for-building-with-picolibc.patch
Resolve conflicts with the changes made by PR #71827.
```
https://github.com/llvm/llvm-project/pull/71827
```
> [patches] Resolve merge conflict with upstream PR 71827

- CMakeLists.txt
- patches/llvm-project/0006-Disable-failing-compiler-rt-test.patch
- test-support/picolibc-test-wrapper.py
Refactor libraries with exceptions
Rework of libraries with exceptions
so one can use them with --sysroot parameter
to clang compiler.
> Fix test failure on CI

- patches/llvm-project/0001-Add-ExclusiveGroup-feature-to-multilib.yam.patch
There is a patch in BMT which fixes the
issue of losing MVE features and an assembler
error for V8.1m Cpus because of that. This
patch has been upstreamed in llvm-project now:
https://github.com/llvm/llvm-project/pull/71545
> Remove the patch as it is upstreamed.

- patches/picolibc.patch
https://github.com/picolibc/picolibc/commit/43a3894158561b568118d31376edb465238fd320 adds support for a small ctype implementation -- an inline version which performs direct character value comparisons without needing a table.
However this implementation does not support locales or extended character sets. Therefore fallback to the classic, table based ctype implementation.
> Disable small versions of ctype functions

- CMakeLists.txt
- cmake/multilib.yaml.in
- test/multilib/armv8.1m.main.test
The extension flags in -march option were separated, to make them more flexible.
The matching expression was improved, so that it does not accidentally catch longer extenstion names, eg. +mve.fp is not matched by +mve.
> multilib: separate the extension flags

- CMakeLists.txt
Rather than use a regex string search on the LLVM CMakeLists.txt, this patch adds the LLVM project as a subdirectory and then reads the version variables as properties. Additionally, this adds some new variables to store packaging information, as including CPack resets many of the variables used to configure CPack.
> Read LLVM version from subdirectory

- CMakeLists.txt
- cmake/multilib.yaml.in
- test/multilib/armv7m.test
The fpu option in test was not applicable to armv7m - fixed to a valid one.
Restored the order of variants and removed the comment. "-mfpu=none" variant will not be selected in case different fpu was specified. Removed a hack in multlib.yaml.in.
> multilib: simplify softfp variant selection

- test-support/llvm-libc++-picolibc.cfg.in
- test-support/llvm-libc++abi-picolibc.cfg.in
- test-support/llvm-libunwind-picolibc.cfg.in
Removed manual definition of LIBCXX-PICOLIBC-FIXME. The upstream scripts detect it automatically.
> Update lit config files to match new variable names used in upstream

- patches/llvm-project/0001-libc-tests-with-picolibc-xfail-two-remaining-tests.patch
- patches/llvm-project/0002-libc-tests-with-picolibc-disable-large-tests.patch
- patches/llvm-project/0003-Disable-failing-compiler-rt-test.patch
- patches/llvm-project/0004-libc-tests-with-picolibc-mark-sort-test-as-long-one.patch
- patches/llvm-project/0005-libc-tests-with-picolibc-XFAIL-uses-of-atomics.patch
- patches/llvm-project/0006-libc-tests-with-picolibc-mark-two-more-large-tests.patch
- patches/llvm-project/0007-libc-tests-with-picoilbc-protect-absent-atomic-types.patch
This fixes the modules.std.compat.pass.cpp test in libc++ test suite for variants which currently have no atomic support, like armv4t.
The refreshed patches apply cleanly to
6d7de46155fece05ab5a44aedd573a811f4b208a.
> libc++ tests: prevent import of absent atomic types

- test-support/llvm-libc++-picolibc.cfg.in
- test-support/llvm-libc++abi-picolibc.cfg.in
- test-support/llvm-libunwind-picolibc.cfg.in
Restore libc-include and libc-lib variables.
Alternatively the tests could depend on multilib_yaml and rely on multilib providing the right paths to C-library.
Fix the order of c and c++ libs
> Fix lit config files for libc++, libc++abi and libunwind

- patches/picolibc.patch
This section was added into libc++ and conains the "new" operator[1]. Placing the "new" operator in the section allows checking, if the operator (defined as weak symbol) was overridden.
The check relies on the "__start_" and "__end_" symbols generated by linker. These symbols would not be generated for names, which are not valid C identifiers. For this reason name like ".text.__lcxx_generated" cannot be used.
[1] https://github.com/llvm/llvm-project/pull/69498
> picolibc: linker script: Add '__lcxx_override' section

- patches/picolibc.patch
The __start___lcxx_override and __stop___lcxx_override symbols were not generated for some tests. This change manually defines those symbols to fix following link error:
```
ld.lld: error: undefined symbol: __start___lcxx_override
>>> referenced by stdlib_new_delete.cpp
```
> picolibc: linker script: force start/stop symbols for __lcxx_override

- CMakeLists.txt
Fix multilib selection process
so process will respect
-fno-exception and -fno-rtti multilib flags
> Fix multilib selection process

- patches/newlib.patch
libc++ std::print function implementation relies on access to POSIX function "fileno", called in __is_posix_terminal. newlib does not expose that function in stdio.h header, unless __POSIX_VISIBLE is defined. Adding _DEFAULT_SOURCE macro enables the __POSIX_VISIBLE macro.
The flag was not added to LIBCXX_EXTRA_SITE_DEFINES, as the stdio.h header could be included before libc++ headers. In such case stdio.h would be parsed without the __POSIX_VISIBLE define and would not be parsed again, because of it's header guards.
I removed forced declaration of `FILE` in `wchar.h` as `_DEFAULT_SOURCE` already enables that.
> newlib: Enable _DEFAULT_SOURCE globally

- CMakeLists.txt
libcxx no longer honours the LIBCXX_EXECUTOR cmake definition. Instead you have to define LIBCXX_TEST_PARAMS=executor=[whatever]. The same goes for libcxxabi.
It looks as if libunwind hasn't yet stopped supporting LIBUNWIND_EXECUTOR, but it's deprecated, so it seems sensible to update all three at once.
> Update executor specification for llvm-runtimes testing.

- CMakeLists.txt
- README.md
Updated the documentation as exceptions and rtti are supported now.
Added add_library_variants_for_cpu function to reduce duplication.
> Separate the flags for exceptions and rtti.

- CMakeLists.txt
- test-support/run-picolibc-tests.py
The wrapper script adds a variant name to the classname for tests in the junit xml results file. The new classname helps distinguish tests, when displayed in Jenkins.
Add check-picolibc_{variant} aliases for picolibc test targets for consistency with other tests.
> Run picolibc tests from a wrapper script

- CMakeLists.txt
- patches/llvm-project/0007-llvm-objcopy-Support-SREC-output-format-75874.patch
This patch is a combined cherry-pick of three LLVM trunk commits: 7ddc32052546abd41656d2e670f3902b1bf805a7
5afbed1968588fe443a8a55053c2f1eaa321d28e
2cbe5a33a5fda257747d75863bd9ccb8920b9249
The first one implements support in llvm-objcopy for writing output in the S-record hex format. The other two are tiny fixes for build failures introduced by the first patch.
These patches were committed on LLVM trunk by the following authors:
7ddc32052546abd (the main patch): quic-areg <aregmi@quicinc.com>
5afbed1968588fe (build fix #1): Jon Roelofs <jonathan_roelofs@apple.com>
2cbe5a33a5fda25 (build fix #2): Maksim Panchenko <maks@fb.com>
> Backport SREC output support in llvm-objcopy.

- CMakeLists.txt
The COMPILER_RT_DEFAULT_TARGET_TRIPLE definition now uses the normalized target triple rather than the target triple argument itself, which has changed the location of libclang_rt. This patch updates the functions that are used to generate the triple names to match, which mostly consists of inserting "-unknown".
> Use normalized target triples

- CMakeLists.txt
A newlib overlay build does not recognise a target triple as normalized by clang, however compiler-rt build needs the normalized triple to find the correct output directory. So this patch uses the normalized triple only for compiler-rt.
> Only use normalized target triple for compiler-rt

- CMakeLists.txt
- cmake/multilib.yaml.in
The way in which clang normalizes certain target triples was recently changed:
https://github.com/llvm/llvm-project/pull/89638
This has the effect of switching the vendor and OS from "none-unknown" to "unknown-none" in the normalized triple, to better reflect that the bare metal target has no OS, rather than an unknown one.
The cmake script and multilib templates have various hardcoded references to triples which now need changing.
> Update target triples affected by normalization change

- CMakeLists.txt
We cannot add both code size and performance library sub-variants for every variant yet, because there is no way to select between them in the multilib file, so some defaults suggested for now.
> Add a way to set size vs performance optimization for library variants

- patches/llvm-project/0002-libc-tests-with-picolibc-disable-large-tests.patch
Applying the 0002-libc-tests-with-picolibc-disable-large-tests.patch llvm-project patch failed because of llvm-project commit 3497500946c9b6a1b2e1452312a24c41ee412b34:
"[libc++] Clean up and update deployment target features (#96312)"
This patch should make the application succeed again.
> fix llvm large test patch application

- CMakeLists.txt
This copies `libc/LICENSE.TXT` from the llvm-project repository into the `third-party-licenses` directory, renamed to `LIBC-LICENSE.TXT` so you can tell it apart from all the other subdirectory licenses. (We were already doing similar renames for libcxx, libunwind, etc.)
When you build the toolchain in llvm-libc-only mode, that file shows up along with all the others at the top level of `third-party-licenses`. If you build an overlay package, it ends up in the `third-party-licenses/llvmlibc` subdirectory.
> When building LLVM libc, include its license file.

- patches/llvm-project/0004-libc-tests-with-picolibc-mark-sort-test-as-long-one.patch
Update patch file for libc++ tests with picolibc, to mark sort test as long one.
> Update patch file for libc++ tests with picolibc, to mark sort test as long one

- CMakeLists.txt
- Omax.cfg
- OmaxLTO.cfg
The motivation for this change is that users
may wish to disable LTO when using the the Omax.cfg
file. Removing the LTO flags to a seperate file allows
the user to enable LTO related flags seperately.
> Separate LTO options from Omax.cfg

- CMakeLists.txt
- README.md
- docs/migrating.md
- packagetest/hello.c
- packagetest/hello.cpp
- samples/Makefile.conf
- samples/src/baremetal-semihosting-aarch64/make.bat
- samples/src/baremetal-semihosting/make.bat
- samples/src/baremetal-uart/Makefile
- samples/src/baremetal-uart/make.bat
- samples/src/cpp-baremetal-semihosting-cfi/make.bat
- samples/src/cpp-baremetal-semihosting-prof/make.bat
- samples/src/cpp-baremetal-semihosting-ubsan/make.bat
- samples/src/cpp-baremetal-semihosting/make.bat
- test-support/llvm-libc++-picolibc.cfg.in
- test-support/llvm-libc++abi-picolibc.cfg.in
- test-support/llvm-libunwind-picolibc.cfg.in
This commit adds the -nostartfiles option to tests using semihosting. This is in response to a recent change in clang which modified the driver to include crt0.o in the link:
https://github.com/llvm/llvm-project/pull/101258
While the change to clang removes the need to include the crt0 library directly, the tests using semihosting need to link against a different crt0 library. Therefore the new default behavior needs to be suppressed in these cases, which can be done by adding the -nostartfiles option.
> Do not default to linking crt0 when using crt0-semihosting

- README.md
Updating the README.md file to detail use case of Omax.cfg and OmaxLTO.cfg.
> Update README to reference Omax.cfg and OmaxLTO.cfg

- CMakeLists.txt
- llvmlibc-support/exit.c
The first two commits in this PR arrange to build the experimental LLVM libc on AArch64 as well as AArch32 (fixing a build failure and then enabling the build).
The other two are minor cleanups, developed together but not strongly related, but too small to bother making a separate PR for.
> Support building LLVM libc on AArch64 (plus minor fixes)

- versions.json
Commit hash e434fa1f41a83a888d6498922ab7f140011933d1 was the last one working. Set it as the default revision while recent breakages are not fixed.
> Set picolibc version to a working revision

- CMakeLists.txt
A header comment in CMakeLists.txt suggests a sequence of commands for manually checking out the source repos and applying the patches. But it doesn't work, because it includes the command
git -C repos/llvm-project am -k ../../patches/llvm-project/*.patch
which, under POSIX shell semantics, is handled by first trying to expand the wildcard, then running the git command, which will change directory into `repos/llvm-project` because of the `-C` option. But the command only works if the wildcard is expanded _after_ changing directory, because the `../..` on the front of the pathname is intended to get back out of `repos/llvm-project`.
To fix this, I've replaced the relative paths with `$PWD`, which will be expanded before git changes directory, so the pathnames will refer to the root of this …
> [CMakeLists] Correct suggested -DFETCHCONTENT_SOURCE_DIR script

- docs/building-from-source.md
In the `Building` section of building-from-source.md, twice we are trying to apply a patch with the following command:
git -C repos/<repo> am -k "$PWD"/../patches/<repo>/*.patch
This command is executed from the root of the repo. The original thought for this must have been that because of the `-C`, our path at time of execution is `repos/<repo>`, and thus we need to move a level up from our current directory. However `$PWD` will be replaced by the shell before the command is executed. So we need to remove the spurious `../`.
> Fix path in build from source recipe

- CMakeLists.txt
- cmake/multilib.yaml.in
This adds the folowing library variants with support for the PACBTI-M
architecture extension:
* armv8.1m.main_soft_nofp_nomve_pacret_bti[_exn_rtti]
* armv8.1m.main_hard_fp_nomve_pacret_bti[_exn_rtti]
* armv8.1m.main_hard_fpdp_nomve_pacret_bti[_exn_rtti]
* armv8.1m.main_hard_nofp_mve_pacret_bti[_exn_rtti]
Unfortunately, qemu currently doesn't provide support for PACBTI-M,
which means these variants can't be fully tested at runtime level.
Since the PACBTI-M instructions are NOP-copatible, we can use an
arvm8.1m.main CPU as a workaround to ensure that the library code
still works correctly regardless of branch protecion.
> Add Armv8.1-M PACBTI library variants

- test-support/picolibc-test-wrapper.py
This adds the `fenv` and `math_errhandling` tests to the set of disabled
tests for the PACBTI-M library variants, introduced by #467.
These tests were already disabled for the previously existing variants,
due to a known issue in compiler-rt where the floating point exceptions
are not set correctly for computations on types implemented in software.
> Add missing set of disabled tests for PACBTI-M variants

- versions.json
Now that the limits.h issue [^1] has been resolved in picolibc upstream [^2], we can go back to its latest HEAD.
[^1]: Commit hash cdc4fc3164cf8ac4c7ff6c4025822b792c7394f8
[^2]: https://github.com/picolibc/picolibc/pull/810
> Use latest HEAD from picolibc

- cmake/multilib.yaml.in
- test/multilib/armv7a.test
- test/multilib/armv7r.test
The instruction set (ARM/Thumb) is included in the triple, but doesn't matter for library selection because the ISA can be switched on any function call. This adds match blocks to multilib.yaml to treat thumb triples as if they were arm triples for library selection.
This will also be needed for AArch32 v8-A and v8-R, but we don't have any libraries for them yet.
> Add multilib mappings for thumb triples

- cmake/multilib.yaml.in
- test/multilib/armv7a.test
This is a GCC name for v7-A with the virtualisation extension, so for library selection we can treat it the same as v7-A.
> Add multilib mappings for armv7ve

- patches/llvm-project/0004-libc-tests-with-picolibc-XFAIL-uses-of-atomics.patch
This patch failed to apply for me in a manual `git am`, because the upstream addition of `ADDITIONAL_COMPILE_FLAGS` was just close enough to our change to confuse git. Regenerated that hunk. Now it still makes the same change, just without complaining.
> Update a downstream patch for altered context (NFC)

- CMakeLists.txt
- test/multilib/aarch64.test
Currently there's only one aarch64-a variant. We would like to add
aarch64-r variants in the future and need a way of distinguishing
between the different profiles.
> Make aarch64-a variant distinct from aarch64-r

- versions.json
Set llvm-project to the current latest release tag (llvmorg-19.1.0-rc4), and picolibc to a known working version.
> Use fixed versions for llvm-project and picolibc

- CMakeLists.txt
- test-support/picolibc-test-wrapper.py
- test/multilib/armv7a.test
- test/multilib/armv7r.test
This patch adds the following library variants.
1. armv7r hard_vfpv3xd
2. armv7a soft_vfpv3_d16.
Also disable the math_errhandling tests to the set of disabled
tests for the armv7r_hard_vfpv3xd library variant.These tests were
already disabled for the previously existing variants, due to a known
issue in compiler-rt where the floating point exceptions are not set
correctly for computations on types implemented in software.
> Add missing armv7 library variants.

- CMakeLists.txt
The order in multilib.yaml matches the order of the libraries in CMakeLists.txt.
At the moment both the below commandline options selecting the same library variant.
```
$ clang -print-multi-directory --target=armv7r-none-eabihf -mfpu=vfpv3-d16
arm-none-eabi/armv7r_hard_vfpv3xd_exn_rtti
$ clang -print-multi-directory --target=armv7r-none-eabihf -mfpu=vfpv3xd
arm-none-eabi/armv7r_hard_vfpv3xd_exn_rtti
``` 
We need to reorder the the add_library_variant calls so that armv7r_hard_vfpv3_d16 gets selected appropriately.
> Reorder the add_library_variant calls for the armv7r_hard_vfpv3_d16 to win

- CMakeLists.txt
- test/multilib/armv7r.test
This patch adds the following library variant.
1. armv7r soft_vfpv3_d16.
Adding tests in test/multilib to make sure that all the newly added library variants  get selected correctly..
> Add missing armv7 library variants

- CMakeLists.txt
- test-support/picolibc-test-wrapper.py
- test/multilib/armv7a.test
- test/multilib/armv7r.test
This patch adds the following library variants.
1. armv7r hard_vfpv3xd
2. armv7a soft_vfpv3_d16.
Also disable the math_errhandling tests to the set of disabled tests for the armv7r_hard_vfpv3xd library variant.These tests were already disabled for the previously existing variants, due to a known issue in compiler-rt where the floating point exceptions are not set correctly for computations on types implemented in software.
Adding tests in test/multilib to make sure that all the newly added library variants  get selected correctly.
> Add missing armv7 library variants. (#464)

- CMakeLists.txt
- test/multilib/armv7r.test
This patch adds the following library variant.
1. armv7r soft_vfpv3_d16.
Adding tests in test/multilib to make sure that all the newly added library variants get selected correctly..
> Add missing armv7 library variants (#491)

- CMakeLists.txt
Follow up to [#467](https://github.com/ARM-software/LLVM-embedded-toolchain-for-Arm/pull/467).
This patch makes picolibc's startup code enable PAC and BTI in the relevant library variants.
picolibc's startup code enables PAC and BTI if and only if __ARM_FEATURE_PAUTH and __ARM_FEATURE_BTI are defined respectively. These macros are defined if `+pacbti` is passed in the `-march` command-line option: it is not enough to use `-mbranch-protection` in the build of the library variant.
> Enable PACBTI in picolibc's startup code

- CMakeLists.txt
Since LLVM libc lacks an AArch64 config, LIBC_CONFIG_PATH is set to the arm subdirectory to force it to use the existing AArch32 config. However, this has the side effect of never loading the generic baremetal config.json file, which is instead in the parent directory.
In order to combine the entrypoints in the arm config with the values set in the generic baremetal config, this patch copies both to the same location to be used in the build.
> Create a custom config for LLVM libc

- CMakeLists.txt
- test/multilib/armv8.1m.main.test
We don't build any MVE-capable libraries with the soft-float ABI. We do have Armv7-M soft-float libraries, but you can't fall back to using those, because MVE requires the FPSCR to be set up specially at startup time, and our v7-M soft-float libraries don't do that.
So, rather than select one of those libraries and silently generate wrong MVE code, we should force an error report instead. This commit arranges that, by using the new FatalError flag recently added to the multilib.yaml mechanism.
We already had a commented-out test for this case, so I've uncommented it and made it expect a compile failure with the custom error message.
> Diagnose an unsupported multilib setup: MVE soft-float.

- CMakeLists.txt
- cmake/multilib.yaml.in
Follow up to [#467](https://github.com/ARM-software/LLVM-embedded-toolchain-for-Arm/pull/467).
This patch fixes the multilib mapping for `-mbranch-protection`.
Firstly, the multilib flag to be inserted should be `-mbranch-protection=standard` as it is the flag expected by the PACBTI-M multilib variants.
Secondly, the PACBTI-M variant should also match to configurations where the branch protection is restricted to only one of PAC or BTI, like in `-mbranch-protection=bti` or `-mbranch-protection=pac-ret`. Before this patch, the variant would only match if both features were requested at the same time. This is safe to do because instructions from either feature have no effect if that feature is disabled at runtime.
> Fix multilib PACBTI mapping

- cmake/multilib.yaml.in
- test/multilib/armv8a.test
- test/multilib/armv8r.test
Cherry-pick of two more commits that missed the branch to enable targetting v8-A AArch32 and v8-R+ AArch32
> Cherry-pick two more commits

- versions.json
LLVM 19 has now been released and tagged as llvmorg-19.1.0
> Update version tag for LLVM 19 release

- CHANGELOG.md
- README.md
* Incorporate changes made for LLVM-18 release.
* Add additional supported targets to README.md.
* Remove experimental from AArch64.
* Update CHANGELOG for changes made since LLVM-18.
> Update README.md and CHANGELOG.md for LLVM-19 release

- CHANGELOG.md
Add missing dash between A and profile to make A-profile.
> Reference A-profile correctly [NFC].

- CMakeLists.txt
This was the intention of the previous patch, but I put the check in the wrong place, so the actual builds of the library variants which need FVPs were disabled, not just the tests.
This doesn't need passing through to the add_newlib or add_llvmlibc functions because we don't run the tests for them yet.
> Build libraries even when FVPs not installed

- CMakeLists.txt
This is a symlink to clang, which makes it act like the C preprocessor by default.
> Add clang-cpp to the distribution

- CMakeLists.txt
This is a cherry-pick of #511 and #512 to the llvm-19 branch.
> Add llvm-strings and clang-cpp to the distribution

- CMakeLists.txt
The clang-cpp symlink (or copy) is created with the ALWAYS_GENERATE flag in clang's cmake, so it always gets installed, meaning we don't need to add it to LLVM_DISTRIBUTION_COMPONENTS.
This was causing windows build failures because the install target was being called for it, but not created. I'm not sure why the Linux build was succeeding despite this, but I've checked that clang-cpp existed in both the Windows and Linux builds of the previous release (18.1.3), so clang-cpp doesn't need to be in this list.
> clang-cpp does not need installing in distribution

- versions.json
LLVM 19.1.1 has now been released and tagged as llvmorg-19.1.1
> Update version tag for LLVM 19.1.1 release

- CMakeLists.txt
- multilib-generate.py
- test/multilib/aarch64.test
- test/multilib/armv8a.test
- test/multilib/armv8r.test
This expands multilib-fpus.py (renaming it) to add Match blocks to split the -march options into two sets of options, which will be more useful for libray matching:
* A -march= option for each minor version less than or equal to the selected one, so that it will be possible to mark a library as requiring one architecture version, and allowing it to be used for any later version. This strips any feature modifiers off the option, so that they can be matched independently of base architecture version.
* A -march option for every feature modifier which is enabled or disabled. This uses the made-up architecture name "armvX", which isn't a valid option, but that doesn't matter to multilib, and this allows matching features independently of the base architecture version.
> Generate multilib.yaml for compatible architecture versions and features

- patches/llvm-project/0001-libc-tests-with-picolibc-xfail-one-remaining-test.patch
- patches/llvm-project/0002-libc-tests-with-picolibc-disable-large-tests.patch
- patches/llvm-project/0003-Disable-failing-compiler-rt-test.patch
- patches/llvm-project/0004-libc-tests-with-picolibc-XFAIL-uses-of-atomics.patch
- patches/llvm-project/0005-libc-tests-with-picolibc-mark-two-more-large-tests.patch
- patches/llvm-project/0006-Clang-Driver-Adjust-test-to-cope-with-unsupported-mu.patch
The clang driver's `print-multi-selection-flags.c` test uses a
combination of command line options in one of its RUN lines for which we
don't have a valid library variant available.
Since the merging of PR #500, this combination of options now trigger an
error to inform the user of an unsupported setup, but this error also
causes the test to fail.
This adds a new patch file for llvm-project to adjust the test
accordingly.
> Adjust clang's multilib flags test to cope with missing variant

- docs/llvmlibc.md
Support for AArch64 has been available for AArch64 in llvm-libc for some time, but the docs still claim this isn't supported.
Also update the instructions for defining the bounds of the heap for when malloc is used.
> Update llvmlibc.md documentation to include AArch64 support and heap.

- CMakeLists.txt
LLVM PR https://github.com/llvm/llvm-project/pull/110804 made this change at the request of a code reviewer of the original patch.
> [multilib.yaml] Rename the FatalError keyword to Error.

- CMakeLists.txt
- patches/llvm-project/0001-libc-tests-with-picolibc-xfail-one-remaining-test.patch
- patches/llvm-project/0002-libc-tests-with-picolibc-disable-large-tests.patch
- patches/llvm-project/0003-Disable-failing-compiler-rt-test.patch
- patches/llvm-project/0004-libc-tests-with-picolibc-XFAIL-uses-of-atomics.patch
- patches/llvm-project/0005-libc-tests-with-picolibc-mark-two-more-large-tests.patch
Due to a recent commit in upstream LLVM, the patch for the
`libcxxabi/test/test_demangle.pass.cpp` test now only applies when using
3-way merge.
This patch rebases the set of patch files in `patches/llvm-project/*` to
apply cleanly on recent commits from llvm/llvm-project.
> Update llvm-project patch files to apply cleanly on more recent commits

- CMakeLists.txt
The mechanism for setting the default installation directory to <BUILDDIR>/install is highly dependent on the order of events in the CMakeLists.txt file. Due to recent shifts in the file this has stopped working.
The CMAKE_INSTALL_PREFIX_INITIALIZED_TO_DEFAULT check must happen immediately after the first invocation of project(...). When the llvm-project directory is included first, it is calling project() and then sets the CMAKE_INSTALL_PREFIX to the system default.
> [CMake] Fix default install directory

- CMakeLists.txt
- test/multilib/armv7r.test
- test/multilib/armv8r.test
We currently build these two library variants for v7-R with the soft-float ABI:
* armv7r_soft_nofp
* armv7r_soft_vfpv3_d16
The first variant can only be used when the target does not have an FPU, because it does not include bootcode to enable the FPU. This means that we don't have any library variants which can be selected for the single-precision-only FPUs when using the soft-float ABI. For the hard-float ABI, we solve this by having separate library variants for vfpv3xd (SP-only) and vfpv3_d16 (SP+DP). This is important for performance, as it allows the math library to use DP instructions where available.
We could do the same thing for the soft-float libraries, however these variants with an FPU are included for completeness, their performance is less important because a user interested …
> Fix library variants for v7-R soft-float ABI

- CMakeLists.txt
- cmake/patch_llvm.py
- docs/building-from-source.md
- patches/llvm-project-perf/0000-Placeholder-commit.patch
This adds a second llvm-project patch directory, intended for performance enhancement patches which can be kept optional to avoid blocking builds if they become out of date with the main branch. A new CMake option controls whether or not to apply the patches, and a new script is included to manage the patching process to make it easier to identify when there is a problem with a patch.
> Add additional patch folder for performance patches

- Omax.cfg
This optimization sees some good improvements and the downstream equivalent is enabled for -Omax on Arm Compiler 6.
> Add -enable-dfa-jump-thread to Omax.cfg

- Omax.cfg
These optimizations see some good improvements and the downstream equivalents are enabled for -Omax on Arm Compiler 6.
> Add Loop Flatten and Unroll and Jam optimizations to Omax cfg

- CMakeLists.txt
- docs/llvmlibc.md
- llvmlibc-samples/src/llvmlibc/baremetal-semihosting/Makefile
- llvmlibc-samples/src/llvmlibc/baremetal-semihosting/crt0llvmlibc.c
- llvmlibc-samples/src/llvmlibc/baremetal-semihosting/hello.c
- llvmlibc-samples/src/llvmlibc/baremetal-semihosting/microbit-llvmlibc.ld
- llvmlibc-samples/src/llvmlibc/baremetal-semihosting/vector.c
This will be built into the LLVM libc overlay package. Sample installs to samples/src/llvmlibc/baremetal-semihosting.
* Add llvmlibc-samples directory to contain LLVM libc specific samples.
* Add single baremetal-semihosting sample using LLVM libc.
Sample contains a number of calls to LLVM libc functionality:
* heap.
* printf.
* string library.
* math library.
A special linker script is used to set the bounds of the heap. This uses different linker defined symbols to picolibc.
The crt0.S from the existing llvmlibc-support can't be used directly as the RW and ZI from the linker script need initializing.
> Add LLVM libc sample

- patches/picolibc.patch
Patch no longer cleanly applies, so this updates the diff.
> Update picolibc patch file

- 0001-Remove-armv4t-armv5t-from-check-all-targets.patch
- 0001-Update-picolibc-patch-file.patch
- CMakeLists.txt
The compiler-rt and libcxx tests for armv4t and armv5t variants currently hang until a timeout is reached. Rather than disable the tests, this patch removes them from the check-all targets. This allows the tests to still be run while investigating the issue, but does not interrupt overall testing of the toolchain.
> Remove armv4t/armv5t from check-all targets

- multilib-generate.py
Building on Ubuntu 24.04, multilib-generate.py provokes some SyntaxWarning messages from Python 3.12, because of cases where we'd written `\+` in a string, intended to be emitted literally. 3.12 still _does_ emit it literally, but prints a warning pointing out that we should properly escape the backslash, writing it as `\\+`.
> Fix Python SyntaxWarning in two f-string literals.

- OmaxLTO.cfg
- docs/optimization-flags.md
The flag to add the extra loop unroll pass was previously provided to opt and was not actually working, as it's supposed to be provided to the LTO plugin.
> [OmaxLTO] Fix the flag to be supplied to the LTO plugin

- patches/llvm-project/0006-Define-_LIBCPP_HAS_C8RTOMB_MBRTOC8.patch
LLVM libcxx does not define the `char8_t` related functions, instead delegating their definitions to the underlying C library.
libcxx defines a macro called `_LIBCPP_HAS_C8RTOMB_MBRTOC8` when it infers that the underlying C library provides these functions.
picolibc provides the `char8_t` related functions regardless of the C++ version used, but this support only landed after version 1.8.8 and, at the time of writing, has not made into any released version yet.
This is a temporary fix and should be removed when a picolibc release includes the support for `char8_t` and its related functions. When it's time to implement a proper solution, one needs to create logic to detect the picolibc version and define the macro accordingly. The macros that govern picolibc version are in `picolibc.h`.
> [libcxx] Add downstream patch to enable `char8_t` related functions

- patches/llvm-project/0007-libcxx-Remove-xfails-due-to-picolibc-s-support-for-c.patch
picolibc added support for `char16_t` on trunk. However we can't yet remove the xfails in upstream because it firstly needs to pick up on a picolibc release that includes that support.
This is a patch which must be upstreamed once llvm-project updates its picolibc version to one that has `char16_t` support.
> [libcxx] Remove xfails for char16_t

- patches/newlib.patch
To check for SME support, compiler-rt makes a call to __aarch64_sme_accessible(). It expects this symbol to be defined in newlib, which is currently incorrect. This patch extends newlib.patch to add the definition of __aarch64_sme_accessible.
> Add aarch64_sme_accessible to newlib patch

- fvp/get_fvps.sh
A new version of Arm's Ecosystem FVPs have been release and, with that,
the links for the older versions are no longer valid.
This updates the get_fvps.sh script to use the links for the new
version.
> Update version of FVPs used for testing

- patches/llvm-project-perf/0002-ARM-Codegen-Set-LDM-STM-inlining-preference-for-v7m.patch
Windows expects newline to have a space
at the end of them. Because of this my updated
patch file failed to build on Windows. This commit adds the appropriate spaces.
> [NFC]Format patch file for Windows

- CMakeLists.txt
- arm-multilib/CMakeLists.txt
- arm-multilib/json/variants/armv8.1m.main_hard_fp_nomve_pacret_bti.json
- arm-multilib/json/variants/armv8.1m.main_hard_fp_nomve_pacret_bti_exn_rtti.json
- arm-multilib/json/variants/armv8.1m.main_hard_fpdp_nomve_pacret_bti.json
- arm-multilib/json/variants/armv8.1m.main_hard_fpdp_nomve_pacret_bti_exn_rtti.json
- arm-multilib/json/variants/armv8.1m.main_hard_nofp_mve_pacret_bti.json
- arm-multilib/json/variants/armv8.1m.main_hard_nofp_mve_pacret_bti_exn_rtti.json
- arm-multilib/json/variants/armv8.1m.main_soft_nofp_nomve_pacret_bti.json
- arm-multilib/json/variants/armv8.1m.main_soft_nofp_nomve_pacret_bti_exn_rtti.json
- arm-runtimes/CMakeLists.txt
Two scripts arguments were renamed during review, but the cmake steps calling the script weren't updated.
Additionally the our downstream test targets such as check-package-llvm-toolchain target require the path to an external llvm-lit in order to run the tests.
> Corrections to CMake changes to enable library sub-builds

- CMakeLists.txt
- docs/building-from-source.md
Now that our downstream picolibc changes are in the form of multiple patches in a subdirectory, it's better to apply them with 'git am' so they turn into separate commits, instead of 'git apply', the same way we do it for llvm-project.
> CMakeLists.txt: tiny fix to instructions comment.

- docs/building-from-source.md
The suggested build commands left out the usual `cd` after `mkdir`, so that if you followed them literally, you'd create an `arm-runtimes` or `arm-multilib` directory and then ignore it completely and put all your build debris at the level above it.
Also, trying to follow the instructions, I was confused by the semantics of `LLVM_BINARY_DIR`: given the name, I instinctively pointed it at the actual `bin` directory, but it turned out I should have aimed one level up. Added some clarifying text, with particular reference to using a full build of this toolchain for a standalone build of one library.
While I'm here, removed some apparently accidental physical tabs, so that all the continuation lines in the long cmake commands line up.
> Docs fixes for arm-runtimes and arm-multilib sub-builds.

- arm-runtimes/test-support/picolibc-test-wrapper.py
- arm-runtimes/test-support/run_fvp.py
This allows picolibc tests to mark themselves as "skipped" by returning the special exit code 77. Previously that didn't work in an FVP test run, so those tests are marked as failed rather than skipped.
In particular, test-sprintf-percent-n was affected, because we build picolibc in a mode that doesn't support printf("%n"), and that test knew it and was trying to return "skipped".
Background: Fast Models does support the SYS_EXIT_EXTENDED semihosting request, which allows specifying an exit status. But it doesn't support the ":semihosting-features" pseudo-file that advertises support for non-default semihosting features including that one. So picolibc wrongly believes that SYS_EXIT_EXTENDED doesn't work, and doesn't try it.
This commit works around that lack of support by simply creating …
> Permit FVP tests to return a useful exit status.

- arm-runtimes/CMakeLists.txt
- patches/picolibc/0002-Add-bootcode-for-AArch64-FVPs.patch
The current picolibc changes can't handle fvp being set as the test machine for anything other than aarch64. If fvp isn't set, it defaults to qemu, which works for now because the ARM fvp doesn't require anything special. 
However, when adding new aarch64 big-endian variants, one of the picolibc patches includes test-machine as an option in the Meson build scripts. Consequently, the library's CMake needs to set this option using -Dtest-machine=${TEST_EXECUTOR}. This means that for the armv8.1m library variant,we are explicitly passing the FPU, which can cause the error fvp: requested test machine not found since fvps are only defined for the aarch64 case.
> Make fvp work for anything other than aarch64 when being set as the test machine

- arm-runtimes/test-support/run_fvp.py
- docs/building-from-source.md
- fvp/get_fvps.sh
Before this patch, running get_fvps.sh --non-interactive would make a weirdly named directory in the user's home, with a name like "". or "." (depending on circumstances), with the crypto plugins installed in it.
Now --non-interactive installs the plugins under fvp/install in your git checkout of this repository, which is where they should have been.
The problem was because of this construction in get_fvps.sh:
INSTALLER_FLAGS_CRYPTO="... --basepath \"$(dirname \"$0\")\""
which has multiple shell errors. Firstly, the \" around $0 are taken literally, so dirname is handed a path beginning with a double quote, which propagates into the path it returns. Secondly, the \" around $(dirname) are also literal, but _not_ reprocessed when $INSTALLER_FLAGS_CRYPTO is expanded on to the installer …
> Fix install directory for FVP crypto plugin.

- arm-multilib/json/multilib.json
- arm-multilib/json/variants/armv7a_soft_nofp_strictalign.json
- arm-multilib/json/variants/armv7a_soft_nofp_strictalign_exn_rtti.json
This is to match with the corresponding aarch64 variant for -mno-unaligned-access.
> Rename the variant name  from strictly_aligned to strictalign.

- arm-multilib/CMakeLists.txt
- arm-runtimes/CMakeLists.txt
- cmake/fetch_picolibc.cmake
Every `CMakeLists.txt` that includes `fetch_llvm.cmake` must also call `find_package(Python3)`, because `fetch_llvm.cmake` tries to run `patch_llvm.py` by prefixing it with the Python interpreter name. The CMakeLists in `arm-multilib` wasn't looking for Python at all, and the one in `arm-runtimes` was looking for it _after_ including `fetch_llvm.cmake`.
Also, `fetch_picolibc.cmake` was not reliably looking in the correct directory for its patches: it was using a path relative to `CMAKE_CURRENT_SOURCE_DIR`, which varies depending which CMakeLists it's invoked by. It should be relative to `CMAKE_CURRENT_LIST_DIR`, as the corresponding llvm and newlib paths already are.
> Fixes to patch application.

- test/multilib/armv7a.test
The `test/multilib/armv7a.test` was looking for the incorrect multilib
directory output when checking the behaviour for the strict align
library variant. This patch fixes this issue.
> Fix print-multi-directory test for strict align variant

- docs/building-from-source.md
Previously FVP testing was enabled or disabled implicitly based on whether an FVP install could be found. This has since been changed to a specific CMake option, however the documentation fails to mention this. The build instructions have now been updated with the new CMake option.
> Document option to enable FVP testing

- arm-runtimes/CMakeLists.txt
Since QEMU is needed to run tests with QEMU, if the program cannot be found the build should stop and an error generated.
> When QEMU testing is enabled, QEMU should be required

- arm-multilib/CMakeLists.txt
The additional_cmake_args variable is used to override the defaults and disable testing so that it can be controlled by the higher-level CMake project. But the variable is currently set only when the tests should be disabled. If the tests do not need to be disabled, the value is not updated and the version from the previous iteration of the loop will be used, potentially incorrectly disabling the tests.
To fix this, clear the value on every loop if not needed.
> Prevent arm-runtime CMake arguments persisting over loops

- CMakeLists.txt
- arm-multilib/CMakeLists.txt
- docs/building-from-source.md
Testing with QEMU is implicitly enabled by default, but configuring the project to run with tests requires QEMU. As testing with QEMU is considered optional, it should be possible to disable tests when QEMU is not available or testing is not needed.
Since there is already an option for controlling FVP testing, this patch adds a similar option for QEMU, ENABLE_QEMU_TESTING, which instead defaults to ON. This can then be turned off when QEMU is not installed, so that configurations where QEMU is expected can suitably detect and show an error when it is missing.
> Add an option to disable QEMU testing

- arm-multilib/json/variants/aarch64a_be_soft_nofp.json
- arm-multilib/json/variants/aarch64a_soft_nofp.json
Those two variants have `-fno-exceptions -fno-rtti` in the configuration file that specifies options for building the library. None of the other library variants is built with this flags, not even the other variants intended for use in _applications_ without exceptions and RTTI.
If you try to build libc++abi with those flags, it fails to build, because `private_typeinfo.cpp` is unconditionally included in the library and unconditionally uses `dynamic_cast`.
(And I assume that it's OK to use `dynamic_cast` in that part of libc++abi if the application will never use RTTI, because then it won't include that object file in the first place.)
> Fix build failures in aarch64a_[be_]soft_nofp variants.

- arm-multilib/CMakeLists.txt
- arm-multilib/json/multilib.json
LLVM-libc does not currently support no-neon soft float on AArch64 targets. To prevent building these until support is available, this patch adds an option to explicitly set which C libraries a variant can be built with. If the option is absent, the default is to build with all library options.
> Do not build AArch64a soft no_fp variants using llvm-libc

- arm-multilib/json/multilib.json
This patch fixes the multilib flags required to select the AArch64 soft nofp variants.
The `+nofp` and `+nosimd` arch extensions are specified in the `-march` or `-mcpu` command line options. Before this patch, the multilib flags specified this part as `-march=armv8-a+nofp+nosimd`, however this does not work for any architecture greater than v8, including point releases, nor does it for any `-mcpu` value whose underlying architecture is greater than v8. In the formed case because any point release would lead to a regular expression mismatch; and in the latter, `-mcpu` option processing introduces extra architecture extensions in the string.
Hence the correct way is to match agains `-march=armvX+nofp` and `-march=armvX+nosimd`. These two multilib flags are inserted by our implementation of …
> Fix multilib flags of AArch64 soft nofp

- patches/llvm-project/0008-library-order-workaround-for-597.patch
This adds a patch file that reverts the order of libraries added on the command line to previously working one to avoid error about duplicate __aeabi_mem* symbols.
This patch will be removed, once we implement a proper permanent solution in llvm-project.
> Add a temporary workaround for 597

- arm-multilib/json/variants/armv4t.json
- arm-multilib/json/variants/armv5te.json
Pull request #109628 automatically turned on frame pointers for leaf functions in Clang when frame pointers are enabled. This triggered a latent bug in picolibc for armv4t and armv5te, which consequentially broke our tests for them.
There is currently a pull request that fixes this bug (https://github.com/picolibc/picolibc/pull/897), but we don't have to wait for this to merge to reinstate the tests, because we recently changed the behaviour of Clang to by default omit frame pointers altogether (https://github.com/llvm/llvm-project/pull/117140), and that is how picolibc is built now. In general the advice is that you shouldn't build AArch32 targets with frame pointers enabled for various reasons.
> Reinstate armv4t and armv5te compiler_rt and libcxx tests

- arm-multilib/json/variants/aarch64a_be.json
- arm-multilib/json/variants/aarch64a_be_exn_rtti.json
We've decided to have just two variants here: one with and one without RTTI and exceptions. We will not have variants across the strict aligment dimension. And since a strictly aligned variant is more compatible than one that's not, this change is made.
> Turn AArch64 big endian variants into strictly aligned

- test/multilib/aarch64.test
The tests check if the same variant is chosen with or without `-mno-unaligned-access`. For AArch64 A-profile big endian we provide only strictly aligned libraries.
> Add tests for AArch64 A-profile big endian library selection

- OmaxLTO.cfg
This patch modifies extends OmaxLTO to make use of extra optimisation flags which affect LTO.
> Extend OmaxLTO options

- arm-runtimes/CMakeLists.txt
Newlib overlay package has calls to init and fini. When building newlib, referencing of _init and _fini has been suppressed by undefining the corresponding macro HAVE_INIT_FINI  and relys on the more modern .init_array and .fini_array. But the name of this macro in newlib has changed from HAVE_INIT_FINI to _HAVE_INIT_FINI, so undefine this macro in the cmake file..
> Undefine the macro _HAVE_INIT_FINI which is defined in newlib.

- arm-runtimes/test-support/lit-exec-fvp.py
This patch gives execution permissions to this Python script and fixes one wrong variable name.
Since this script is used as an executable in our lit tests, it ought to have execution rights.
> Fix issues with lit-exec-fvp.py

- arm-runtimes/CMakeLists.txt
Testing the llvm-libc build after the previous commit, I found that the arm-multilib cmake script unconditionally tries to invoke build targets like `cxxlibs-configure` or `cxxlibs-build` in the individual library variant builds. Those targets don't exist in an llvm-libc build, because those set `"ENABLE_CXX_LIBS": "OFF"` in their per-variant JSON files.
This commit applies the simplest possible fix: _make_ targets of those names in `arm-runtimes`, even if nothing is actually in them. Then invoking them from the higher-level build script is a NOP instead of a failure.
> llvm-libc build: fix build failure with C++ libs disabled

- versions.json
As this repo is getting depreciated, pinning picolibc to a specific commit, as we don't want to keep fixing merge conflicts and other unforeseen issues.
> Pin picolibc to specific known to work commit
