ARM-software/LLVM-embedded-toolchain-for-Arm

- scripts/.pylintrc
- scripts/.style.yapf
- scripts/repos.py
- scripts/setup.py
This series of patches refactors the Python scripts as follows:
- makes the scripts comply to pep8
- adds pylint configuration and makes fixes all pylint warnings
- fixes some other style issues.
> Python scripts overhaul

- scripts/build.py
- scripts/config.py
- scripts/repos.py
- scripts/util.py
1. Update logging in repos.py
2. Fix a bug in config.py
> More updates/fixes for Python build scripts

- README.md
- samples/Makefile.conf
- scripts/.pylintrc
- scripts/.style.yapf
- scripts/build.py
- scripts/check.py
- scripts/config.py
- scripts/execution.py
- scripts/make.py
- scripts/repos.py
- scripts/setup.py
- scripts/util.py
The first two patches fix the code base to pass more linters (flake8 which checks PEP 8 conformance and mypy which checks type annotations). The third one fixes the code samples build.
> Miscellaneous fixes

- scripts/make.py
Since LLVM commit https://reviews.llvm.org/D98452 the Arm compiler-rt
library names no longer include the full architecture name
(e.g. armv6m), but rather just "arm" or "armhf". This does not work
correctly with our configuration of Clang (the driver uses the full
architecture name).
This patch adds a step which renames the installed compiler-rt
libraries so that their names match the names generated by Clang.
> Rename compiler-rt libraries after installation

- scripts/config.py
- scripts/execution.py
- scripts/make.py
- 'build.py -v test' failed with incorrect type exception.
- 'build.py all test' did not run tests.
> Fix bugs in 'test' action

- scripts/build.py
- scripts/config.py
- scripts/make.py
- scripts/repos.py
> Corrected several issues highlighted by pylint

- .github/workflows/lint.yml
- README.md
- lint-requirements.txt
- run-precommit-checks.sh
This change:
- Adds a shell script to run precommit checks on Python scripts and
mentions it in the README.md file
- Adds a Github workflow which runs the same checks on pull requests
and updates on the 'main' branch
> Add automated checks for build scripts

- samples/src/cpp-baremetal-semihosting/Makefile
- samples/src/cpp-baremetal-semihosting/README.md
- samples/src/cpp-baremetal-semihosting/hello.cpp
- samples/src/cpp-baremetal-semihosting/make.bat
- scripts/cfg_files.py
Changes have been tested on Linux, msys2 and Windows (PowerShell).
> Reintroduce --sysroot in config files and add one C++ sample

- scripts/repos.py
No need for the whole history so let's clone only the requested
revision. This speeds up the clone significantly and reduce the required
disk space.
> Create a shallow clone of the dependent repositories.

- scripts/config.py
- scripts/make.py
- scripts/package.py
* Implement packaging of docs
* Remove some unused functionality
> Miscellaneous packaging improvements

- scripts/package.py
This patch implements copying of LICENSE.txt and third-party licenses
to binary packages.
The toolchain uses the following third-party components:
- LLVM
- Clang
- lld
- libc++
- libc++abi
- Newlib (including libgloss)
Their licenses are collected into the third-party-licenses directory
and are listed in the file THIRD-PARTY-LICENSES.txt.
> Add license files to binary packages

- patches/llvm-HEAD.patch
- scripts/check.py
- scripts/repos.py
- versions.yml
These patches are the first in a series. The goal of the series is to fix the build failure of the HEAD version.
> Fix HEAD build

- docs/building-from-source.md
Also use a consistent shell prompt character
> Add Ninja to list of build prerequisites

- scripts/make.py
libunwind is a perquisite to have exceptions for example.
> Build libunwind instead of a dummy one.

- samples/README.md
- samples/src/baremetal-semihosting/README.md
- samples/src/baremetal-semihosting/hello.c
- samples/src/baremetal-uart/README.md
- samples/src/cpp-baremetal-semihosting/README.md
- samples/src/cpp-baremetal-semihosting/hello.cpp
SystemInit() us not used by ``picolibc`` so removing from the samples to avoid confusion.
> Remove SystemInit() that was used by newlib and update README

- samples/src/cpp-baremetal-semihosting/hello.cpp
This works now since locale support was added.
> Make C++ example use iostream

- CMakeLists.txt
- patches/llvm-HEAD.patch
A couple of changes landed in llvm-project which means we can remove some workarounds. See commits for details.
> Updates for changes in llvm-project

- patches/picolibc-HEAD.patch
Picolibc has been updated to work with lld:
* https://github.com/picolibc/picolibc/commit/f6940111c56be380e0c3b0ba3f6556b383ef095d
* https://github.com/picolibc/picolibc/commit/4d886deb2e692d90bf2c16fabc196afe641d9215
> Remove picolibc.ld.in patch

- CMakeLists.txt
- cmake/config.cfg.in
This is a small step towards removing the need for config files
> Make lld the default linker

- CMakeLists.txt
- samples/ldscripts/aarch64.ld
- samples/ldscripts/armv6m_soft_nofp.ld
- samples/ldscripts/armv7em_hard_fpv4_sp_d16.ld
- samples/ldscripts/armv7em_hard_fpv5_d16.ld
- samples/ldscripts/armv7em_soft_nofp.ld
- samples/ldscripts/armv7m_soft_nofp.ld
- samples/ldscripts/armv8.1m.main_hard_fp.ld
- samples/ldscripts/armv8.1m.main_hard_nofp_mve.ld
- samples/ldscripts/armv8.1m.main_soft_nofp_nomve.ld
- samples/ldscripts/armv8m.main_hard_fp.ld
- samples/ldscripts/armv8m.main_soft_nofp.ld
Picolibc tests build, executed with shell script
Picolibc tests executed with test parameter
> Picolibc build with llvm-toolchain, run tests.

- patches/picolibc.patch
See https://github.com/picolibc/picolibc/pull/435
> Remove part of picolibc patch that has landed upstream

- CHANGELOG.md
- README.md
- docs/building-from-source.md
> [Docs] Windows packages are now built on Windows

- CMakeLists.txt
- samples/src/cpp-baremetal-semihosting-prof/Makefile
- samples/src/cpp-baremetal-semihosting-prof/README.md
- samples/src/cpp-baremetal-semihosting-prof/hello.cpp
- samples/src/cpp-baremetal-semihosting-prof/make.bat
- samples/src/cpp-baremetal-semihosting-prof/proflib.c
This sample is based on the discussion and the minimal runtime implementation provided by @smithp35 in https://github.com/ARM-software/LLVM-embedded-toolchain-for-Arm/issues/197
> Add bare-metal profiling sample

- CMakeLists.txt
- cmake/to_meson_list.cmake
The function now accepts named arguments. This will make the calls more readable, even when more arguments will be added.
> Extract add_library_variant function

- CMakeLists.txt
The code to construct the test executor was duplicated in three
functions.
> Extract get_test_executor function

- CHANGELOG.md
- README.md
* multilib
* Building from sources created by git archive
> Update readme & changelog

- CHANGELOG.md
- CMakeLists.txt
- cmake/copy_target_libraries.py
- docs/building-from-source.md
This reduces the size of the package file by about a third.
On a machine with many CPU cores, it reduces the elapsed time to perform the compression also by about a third.
> XZ package compression

- test-support/picolibc-test-wrapper.py
> [picolibc] disable one more test failing due to floating point exceptions

- test-support/picolibc-test-wrapper.py
Disable failing test for time of investigation.
> Disable test-fma from picolbic

- test/multilib/armv7m.test
Add a unit test for the armv7m_soft_fpv4_sp_d16 multilib
> [BMT] add armv7m_soft_fpv4_sp_d16 multilib unit test

- CMakeLists.txt
- cmake/multilib.yaml.in
- test-support/picolibc-test-wrapper.py
- test/multilib/armv7m.test
Cherry-pick the armv7m_soft_fpv4_sp_d16 libc variant to the LLVM-17 branch
> Add armv7m_soft_fpv4_sp_d16 libc variant to the LLVM-17 branch

- test-support/picolibc-test-wrapper.py
Picolibc tests for armv8m.main_hard_dp due to
explicit mfpu configuration.
> Enable more Picolibc tests

- CMakeLists.txt
- README.md
- packagetest/hello.c
- packagetest/hello.cpp
- samples/Makefile.conf
- samples/src/baremetal-semihosting/make.bat
- samples/src/baremetal-uart/make.bat
- samples/src/cpp-baremetal-semihosting-cfi/make.bat
- samples/src/cpp-baremetal-semihosting-prof/make.bat
- samples/src/cpp-baremetal-semihosting-ubsan/make.bat
- samples/src/cpp-baremetal-semihosting/make.bat
- test-support/picolibc-test-wrapper.py
- test/multilib/armv4t.test
- test/multilib/armv5e.test
- test/multilib/armv6m.test
- test/multilib/armv8.1m.main.test
- test/multilib/armv8m.main.test
* Add explicit "-mfpu=" for AArch32 commands
Added single precision version for v8.1m.main.
> Add explicit "-mfpu=" for AArch32 commands (#305)

- CHANGELOG.md
- versions.json
This should go in if #322 goes in.
> Update CHANGELOG and picolibc version

- README.md
Fixes https://github.com/ARM-software/LLVM-embedded-toolchain-for-Arm/issues/325
> Fix link to LLVM releases

- README.md
The details remain for reference in respective branches.
> Remove pre-LLVM 17 behavior description

- CMakeLists.txt
Reverts ARM-software/LLVM-embedded-toolchain-for-Arm#330
> Revert "Enable exceptions in libcxxabi"

- CMakeLists.txt
> Fix name for one of the llvm-project patches

- CMakeLists.txt
- patches/llvm-project/0004-xfail-two-remaining-libcxx-with-picolibc-tests.patch
Exceptions for libcxx and rtti has to be enabled together.
> Enable cxx exceptions and rtti.

- patches/llvm-project/0001-Fix-llvm-test-CodeGen-ARM-build-attributes.ll-test.patch
- patches/llvm-project/0002-Add-check-for-building-with-picolibc.patch
- patches/llvm-project/0003-Run-picolibc-tests-with-qemu.patch
One of the patches is also updated to the latest version of upstream review.
> llvm-project patches rebase

- patches/llvm-project/0001-Fix-llvm-test-CodeGen-ARM-build-attributes.ll-test.patch
- patches/llvm-project/0002-Add-check-for-building-with-picolibc.patch
- patches/llvm-project/0003-Run-picolibc-tests-with-qemu.patch
- patches/llvm-project/0004-xfail-two-remaining-libcxx-with-picolibc-tests.patch
patches for libcxx tests are updated to the versions in reviews
> Refresh patches to llvm-project

- CMakeLists.txt
- patches/llvm-project/0001-Fix-llvm-test-CodeGen-ARM-build-attributes.ll-test.patch
- patches/llvm-project/0002-Add-check-for-building-with-picolibc.patch
- patches/llvm-project/0003-Run-picolibc-tests-with-qemu.patch
- patches/llvm-project/0004-xfail-two-remaining-libcxx-with-picolibc-tests.patch
- patches/llvm-project/0005-disable-large-tests.patch
update patches to versions in upstream review
> libcxxabi tests: disable large tests

- patches/llvm-project/0001-Add-ExclusiveGroup-feature-to-multilib.yaml.patch
- patches/llvm-project/0002-Add-check-for-building-with-picolibc.patch
- patches/llvm-project/0003-Run-picolibc-tests-with-qemu.patch
- patches/llvm-project/0004-xfail-two-remaining-libcxx-with-picolibc-tests.patch
- patches/llvm-project/0005-disable-large-tests.patch
- patches/llvm-project/0006-Disable-failing-compiler-rt-test.patch
- patches/llvm-project/0007-libc-tests-with-picolibc-handle-stdin.patch
- patches/llvm-project/0008-libc-tests-with-picolibc-add-has-compolete-fenv-feat.patch
- patches/llvm-project/0009-libc-tests-with-picolibc-Fix-expected-error-message.patch
- patches/llvm-project/0010-libc-tests-with-picolibc-Fix-iterator-diff_type-to-s.patch
- patches/llvm-project/0011-libc-tests-with-picolibc-mark-sort-test-as-long-one.patch
- patches/llvm-project/0012-libc-tests-with-picolibc-XFAIL-uses-of-atomics.patch
- patches/llvm-project/0013-libc-tests-with-picolibc-mark-two-more-large-tests.patch
- patches/llvm-project/0014-libc-tests-with-picolibc-xfail-test-missing-rt-libra.patch
Two patches updated to versions in upstream review.
> Refresh patches to resolve conflicts

- test/multilib/aarch64.test
- test/multilib/armv4t.test
- test/multilib/armv5e.test
- test/multilib/armv6m.test
- test/multilib/armv7a.test
- test/multilib/armv7em.test
- test/multilib/armv7m.test
- test/multilib/armv7r.test
- test/multilib/armv8.1m.main.test
- test/multilib/armv8m.main.test
Added failing test for softfp + armv8.1m.main+mve.
Added {{$}} not to match longer variant names.
> More tests for multilib selection

- CMakeLists.txt
Reverts ARM-software/LLVM-embedded-toolchain-for-Arm#395
> Revert "Include runtime check targets"

- docs/building-from-source.md
Fixes https://github.com/ARM-software/LLVM-embedded-toolchain-for-Arm/issues/404
> Fix example build from source command lines

- packagetest/cpp-baremetal-semihosting-exceptions.test
- samples/src/cpp-baremetal-semihosting-exceptions/Makefile
- samples/src/cpp-baremetal-semihosting-exceptions/README.md
- samples/src/cpp-baremetal-semihosting-exceptions/hello-exn.cpp
- samples/src/cpp-baremetal-semihosting-exceptions/hello.cpp
Add a sample to test C++ exceptions support
> Add a sample to test C++ exceptions support (#432)

- CMakeLists.txt
- Omax.cfg
Introduced a configuration file which enables several optimisation flags.
> Added Omax optimisation cfg file

- README.md
Update pre-requisite for executing on Windows 10 and Windows 11
> Update pre-requisite for executing on Windows 10 and Windows 11

- test/multilib/armv7a.test
- test/multilib/armv7r.test
Use a different check prefix for the newly added tests.
> Fixing the multilib tests introduced by #464

- samples/src/cpp-baremetal-semihosting-exceptions/Makefile
- samples/src/cpp-baremetal-semihosting-exceptions/make.bat
- samples/src/cpp-baremetal-semihosting-prof/make.bat
Added missing make.bat for cpp-baremetal-semihosting-exceptions
Small fix to make.bat in cpp-baremetal-semihosting-prof
> Windows sample fixes

- CHANGELOG.md
- versions.json
Reflect changes in the CHANGELOG.md
> Update LLVM tag to 19.1.5

- CMakeLists.txt
- patches/llvm-project/0011-libcxx-Make-std--unique-lock-available.patch
Add commit e9d5842ac7bd from upstream as patch.
Closes: #555
> Make std::unique_lock available

- patches/llvm-project-perf/0001-LTOpasses-add-loop-unroll.patch
> Fix performance patch no longer applying due to upstream change
